/* Four calendar months, deliberate revision and in-page execution traces. */
(() => {
  'use strict';
  const K=ForgeLearningCore,C=ForgeCatalogCore;
  const curriculum=JSON.parse(document.getElementById('four-month-curriculum').textContent);
  const demos=JSON.parse(document.getElementById('solution-demos').textContent);
  const videos=JSON.parse(document.getElementById('selected-walkthroughs').textContent);
  const oldRender=render,oldToday=todayView;
  let controller=null,trace=null,step=0,playTimer=null,pdfURL='';
  const results=new Map();
  const w=id=>ForgeStudy.workspace(id),settings=()=>state.study;
  const commit=id=>{ForgeWorkspaceStorage?.touch(id);save();};
  const title=id=>ForgeStudy.allProblems().find(p=>p.id===id)?.title||id;
  function queueRepair(id,reason){const x=w(id);x.review=K.repair(x.review,reason,Date.now());commit(id);}
  function recorded(id,attempt,confidence){const x=w(id);x.review=K.afterAttempt(x.review,{...attempt,confidence,timebox:x.timebox||settings().minutesPerProblem},attempt.at);x.timer=null;commit(id);}
  function due(){return Object.entries(settings().workspaces).filter(([,x])=>x.review&&x.review.due<=Date.now()).sort((a,b)=>a[1].review.due-b[1].review.due).map(([id,x])=>({id,...x.review}));}
  function reviewPanel(){const items=due();return `<section class="card pad revision-panel"><div class="between wrap"><div><span class="eyebrow muted">REBUILD FROM MEMORY</span><h2>${items.length} problem re-solves due</h2></div><a class="btn" href="#practice">Problem library</a></div><p class="small muted">Recode before revealing help. Clear independent re-solves grow the interval through 1, 3, 7, 14 and 30 days. Early repeats do not move the due date.</p>${items.slice(0,12).map(x=>`<a class="daily-task" href="#problem/${x.id}"><span><b>${esc(title(x.id))}</b><small>${esc(x.reasons.map(r=>K.reasons[r]).join(' · '))}</small></span><span>Re-solve →</span></a>`).join('')||'<p class="small muted">No problem re-solves are due. New mistakes will return here tomorrow.</p>'}</section>`;}
  function toolsPanel(id,x){return `<section class="card pad practice-controls"><div class="between wrap"><h2>Attempt, test, understand</h2><span class="pill" id="practice-timer">${x.timer?'Timer running':'No timer running'}</span></div><div class="flex wrap"><label>Attempt limit <input class="minutes-input" aria-label="Attempt time limit" type="number" min="5" max="180" value="${x.timebox||settings().minutesPerProblem}" onchange="ForgeLearning.timebox('${id}',this.value)"> minutes</label><button class="btn small" onclick="ForgeLearning.startTimer('${id}')">${x.timer?'Restart timer':'Start timer'}</button><button class="btn small" onclick="ForgeLearning.unclear('${id}')">I do not fully understand</button></div><p class="small muted">A missed time limit, failed test or low-confidence attempt schedules a re-solve. Service outages do not count as code mistakes.</p>${x.review?`<p class="small"><b>Next re-solve:</b> ${new Date(x.review.due).toLocaleDateString()} · ${esc(x.review.reasons.map(r=>K.reasons[r]).join(', '))}</p>`:''}<details><summary>Saved test suite (${x.tests?.length||0}/10)</summary><p class="small muted">Save the current input and expected output, including an intentionally empty answer. Add boundaries and counterexamples. Each test starts a fresh program.</p><button class="btn small" onclick="ForgeLearning.addTest('${id}')">Save current test</button><div>${(x.tests||[]).map((t,i)=>`<div class="saved-test"><b>Test ${i+1}</b><button class="textbtn" onclick="ForgeLearning.removeTest('${id}',${i})">Remove</button><pre>Input: ${esc(t.stdin)}\nExpected: ${esc(t.expected)}</pre></div>`).join('')}</div><div class="flex wrap"><button class="btn primary" onclick="ForgeLearning.runSuite('${id}')">Run saved tests</button><button class="btn" onclick="ForgeLearning.stop()">Stop tests / trace</button></div><pre id="suite-result" class="output" aria-live="polite">${esc(results.get(id)||'Saved tests check your cases, not the platform’s hidden judge.')}</pre></details>${demos[id]?`<details><summary>Original runnable solution and visualization</summary><p class="small muted">Reveal after your own attempt. Includes a complete Python driver and original test cases.</p><button class="btn" onclick="ForgeLearning.demo('${id}')">Reveal & trace solution</button><button class="btn small" onclick="ForgeLearning.loadDemo('${id}')">Load solution + tests</button></details>`:''}</section>`;}
  function tick(){
    for(const [id,x] of Object.entries(settings().workspaces))if(x.timer&&!x.timer.fired&&Date.now()>=x.timer.deadline){x.timer.fired=true;queueRepair(id,'time');if(location.hash==='#problem/'+id)toast('Time limit reached. This problem is scheduled for revision.');}
    const id=location.hash.split('/')[1],x=settings().workspaces[id],node=document.getElementById('practice-timer');
    if(node&&x?.timer){const seconds=Math.max(0,Math.ceil((x.timer.deadline-Date.now())/1000));node.textContent=seconds?`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')} remaining`:'Time is up · revision scheduled';}
  }
  function addTest(id){const x=w(id);x.tests=x.tests||[];if(x.tests.length>=10){toast('Use up to ten test cases per problem.');return;}if(x.stdin.length>16000||x.expected.length>50000){toast('This test exceeds the saved input/output limit.');return;}x.tests.push({stdin:x.stdin,expected:x.expected});commit(id);render();}
  async function runSuite(id){
    if(controller||ForgeStudy.isRunning()){toast('Stop the current run first.');return;}const x=w(id);if(!x.tests?.length){toast('Save at least one test first.');return;}
    if(!['python','javascript'].includes(x.language)&&!ForgeNative.isConnected()){ForgeNative.connectDialog();return;}
    const ctx=new AbortController();controller=ctx;const source=x.drafts[x.language],language=x.language,tests=x.tests.map(t=>({...t}));let lines=[];
    try{for(let i=0;i<tests.length;i++){
      const node=document.getElementById('suite-result');if(node)node.textContent=lines.join('\n')+`\nRunning test ${i+1}/${tests.length}…`;
      const result=await ForgeRunner.execute({language,source,stdin:tests[i].stdin},ctx.signal);
      const check=K.compare(result,tests[i].expected);if(check.reason)queueRepair(id,check.reason);
      lines.push(`Test ${i+1}: ${check.pass?'PASS':check.reason?'FAIL':'SERVICE ERROR'} (${result.status})${check.pass?'':'\nExpected: '+tests[i].expected+'\nReceived: '+(result.stdout||'')+'\n'+(result.compileOutput||result.error||result.stderr||'')}`);
      if(!check.reason&&!check.pass)break;
    }}catch(e){lines.push(e.name==='AbortError'?'Stopped.':e.message);}finally{controller=null;results.set(id,lines.join('\n\n'));if(location.hash==='#problem/'+id)render();}
  }
  function displayValue(value){
    if(typeof value==='string')return `<code>${esc(value)}</code>`;
    return `<div class="trace-value"><small>${esc(value.type)} @${esc(value.ref)}</small><div class="trace-cells">${value.items.map((v,i)=>`<span class="trace-cell"><small>${i}</small>${Array.isArray(v)?displayValue(v[0])+' → '+displayValue(v[1]):displayValue(v)}</span>`).join('')}${value.more?'<span>…</span>':''}</div></div>`;
  }
  function paintTrace(){
    const target=document.getElementById('trace-body');if(!target||!trace){clearInterval(playTimer);return;}
    const item=trace.result.steps?.[step];
    target.innerHTML=`<div class="trace-controls"><button class="btn small" onclick="ForgeLearning.move(-1)" ${step===0?'disabled':''}>← Back</button><button class="btn small" onclick="ForgeLearning.play()">Play / pause</button><button class="btn small" onclick="ForgeLearning.move(1)" ${step>=(trace.result.steps?.length||0)-1?'disabled':''}>Next →</button><input aria-label="Execution step" type="range" min="0" max="${Math.max(0,(trace.result.steps?.length||0)-1)}" value="${step}" oninput="ForgeLearning.seek(this.value)"><span>Step ${item?step+1:0}/${trace.result.steps?.length||0} · ${esc(item?.event||trace.result.status)}</span></div><p class="small muted">A line event shows memory <b>before</b> that line runs. Shared @ numbers identify shared objects. Large values and long traces are capped.</p><div class="trace-layout"><pre class="trace-code">${trace.source.split('\n').map((line,i)=>`<span class="trace-line ${item?.line===i+1?'active':''}"><small>${i+1}</small>${esc(line)||' '}</span>`).join('')}</pre><div class="trace-stack">${(item?.frames||[]).map(frame=>`<section class="card pad"><h3>${esc(frame.name)} · line ${frame.line}</h3>${Object.entries(frame.values).map(([name,value])=>`<div class="trace-variable"><b>${esc(name)}</b>${displayValue(value)}</div>`).join('')||'<p>No local values yet.</p>'}</section>`).join('')||'<p>No executable steps captured. A function or class solution needs a test call to exercise its body.</p>'}${item?.returnValue?`<p>Return: ${displayValue(item.returnValue)}</p>`:''}${item?.error?`<p class="feedback bad">${esc(item.error)}</p>`:''}</div></div><p class="small muted">${trace.result.traceTruncated?'Trace limited to 300 events or 1.5 MB; simplify the input to inspect the rest.':''}</p><h3>Final program output</h3><pre class="output">${esc(trace.result.stdout||'')}${esc(trace.result.error||trace.result.stderr||'')}</pre>`;
  }
  async function visualize(id,source,stdin){
    if(controller||ForgeStudy.isRunning()){toast('Stop the current run first.');return;}const x=w(id);
    if(source===undefined&&x.language!=='python'){
      const label=ForgeNative.languages().find(l=>l.id===x.language)?.label||'';
      const lang=x.language==='javascript'?'js':/^Java \(/.test(label)?'java':x.language;
      if(!['c','cpp','js','java'].includes(lang)){toast('Step visualization is available for Python, C, C++, JavaScript and Java. This runtime can still run saved tests.');return;}
      ForgeStudy.displayTutor(x.drafts[x.language],lang,x.stdin);return;
    }
    source=source??x.drafts.python;stdin=stdin??x.stdin;
    const ctx=new AbortController();controller=ctx;clearInterval(playTimer);
    modal(modalHead('Trace execution inside Forge')+'<p id="trace-loading" class="muted">Loading Python and recording a bounded trace…</p><button class="btn" onclick="ForgeLearning.stop()">Stop trace</button><div id="trace-body"></div>');document.querySelector('.modal')?.classList.add('wide-modal');
    try{const result=await ForgeRunner.execute({language:'python',source,stdin,trace:true},ctx.signal);if(!document.getElementById('trace-body'))return;trace={source,result};step=0;document.getElementById('trace-loading').remove();paintTrace();}
    catch(e){const node=document.getElementById('trace-loading');if(node)node.textContent=e.name==='AbortError'?'Trace stopped.':e.message;}finally{controller=null;}
  }
  function demo(id){ForgeStudy.markHelp(id);const d=demos[id];if(!d)return;modal(modalHead('Original solution: '+title(id))+`<p>${esc(d.explanation)}</p><p><b>${esc(d.complexity)}</b></p><pre>${esc(d.source)}</pre><p class="small muted">Original Forge example · CC0. This is a guided study attempt.</p><button class="btn primary" onclick="ForgeLearning.traceDemo('${id}')">Trace this solution</button>`);}
  function loadDemo(id){const x=w(id),d=demos[id];if(!d)return;ForgeStudy.markHelp(id);x.language='python';x.drafts.python=d.source;x.stdin=d.tests[0].stdin;x.expected=d.tests[0].expected;x.tests=d.tests.map(t=>({...t}));commit(id);render();toast('Original solution and test driver loaded. This attempt is guided.');}
  function weekView(){
    const s=settings(),index=K.block(s.start,today(),C),all=new Map(ForgeStudy.allProblems().map(p=>[p.id,p]));
    return pageHead('FOUR MONTHS · SIXTEEN STUDY BLOCKS','Build understanding that lasts.','Five learning days, one timed practice day and one repair day per block. Extra calendar days belong to catch-up and revision.',`<a class="btn" href="#roadmap">Daily plan</a>`)+`<section class="card pad book-banner"><h2>C track: ${esc(curriculum.book.title)}</h2><p>Brian W. Kernighan and Dennis M. Ritchie · second edition</p><p class="small muted">${esc(curriculum.book.modernC)}</p><label class="btn">Open your own book here<input type="file" accept="application/pdf,.pdf" hidden onchange="ForgeLearning.openBook(this.files[0]);this.value='' "></label><p class="small muted">Choose your PDF to read it inside Forge. The file stays in this tab and is not uploaded.</p></section><div class="month-grid">${curriculum.weeks.map((week,i)=>{
      const monthStart=C.addMonths(s.start,week.month-1),start=plusDays(monthStart,((week.week-1)%4)*7),end=(week.week%4===0?C.addMonths(s.start,week.month):plusDays(start,7));
      return `<article class="card pad study-week ${i===index?'current-week':''}" id="week-${week.week}"><span class="eyebrow muted">MONTH ${week.month} · BLOCK ${week.week} · ${start}–${end}</span><h2>${esc(week.title)}</h2>${s.primaryLanguage==='c'?`<p><b>K&R reading:</b> ${esc(week.bookReading)}</p><p class="small muted">Book exercises: ${week.bookExercises.map(esc).join(', ')||'Re-solve your missed exercises'}</p>`:''}<ul>${week.objectives.map(o=>`<li>${esc(o)}</li>`).join('')}</ul><p><b>Build:</b> ${esc(week.project)}</p><div class="month-links">${week.lessons[s.primaryLanguage].filter(id=>L(id)||ForgeStudy.nativeLessons.some(l=>l.id===id)).map(id=>`<a class="pill" href="#${L(id)?'learn':'native'}/${id}">${esc(L(id)?.title||ForgeStudy.nativeLessons.find(l=>l.id===id)?.title)}</a>`).join('')}</div><h3>Selected practice</h3><div class="week-problems">${week.problems.map(id=>`<a href="#problem/${id}">${esc(all.get(id)?.title||id)} <small>${esc(all.get(id)?.platform||'')}</small></a>`).join('')}</div><details><summary>Seven-day rhythm</summary><ol>${week.days.map(day=>`<li>${esc(day)}</li>`).join('')}</ol></details></article>`;
    }).join('')}</div><p class="small muted">${esc(curriculum.calendarNote)} Preview any task; the daily recommendations still respect prerequisites and demonstrated difficulty.</p>`;
  }
  function enrich(p){if(videos[p.id]&&!p.video)p.video=videos[p.id];return p;}
  function currentIDs(){return curriculum.weeks[K.block(settings().start,today(),C)].problems;}
  function nextBook(){const block=curriculum.weeks[K.block(settings().start,today(),C)];return settings().primaryLanguage==='c'?`<a class="quick-link" href="#curriculum">K&R: ${esc(block.bookReading)} · ${esc(block.title)} →</a>`:'';}
  todayView=function(){return oldToday().replace(/YOUR (?:FIRST|SECOND) STAGE · DAY \d+ \/ 40/g,'YOUR FOUR-MONTH LEARNING PLAN');};
  render=function(){tick();const route=location.hash.slice(1).split('/')[0];if(route==='curriculum'){updateChrome();$('#crumb').textContent='Four-month curriculum';$('#app').innerHTML=weekView()+footer();document.title='Forge · Four-month curriculum';return;}oldRender();if(['roadmap','review'].includes(route)){const node=document.createElement('div');node.innerHTML=reviewPanel();$('#app').prepend(node);}if(route==='native'&&location.hash==='#native/c'){const node=document.createElement('div');node.className='banner';node.innerHTML='<b>Your C reading track:</b> Kernighan & Ritchie, second edition. <a href="#curriculum">Open chapter-by-chapter curriculum →</a>';$('#app').prepend(node);}};
  window.ForgeLearning={toolsPanel,queueRepair,recorded,due,enrich,currentIDs,nextBook,weekView,reviewPanel,visualize,demo,loadDemo,traceDemo:id=>{const d=demos[id];ForgeStudy.markHelp(id);visualize(id,d.source,d.tests[0].stdin);},busy:()=>!!controller,
    addTest,removeTest:(id,i)=>{w(id).tests.splice(i,1);commit(id);render();},runSuite,
    timebox:(id,value)=>{const n=Number(value);if(Number.isFinite(n)&&n>=5&&n<=180){w(id).timebox=n;commit(id);}else toast('Choose a limit from 5 to 180 minutes.');},
    startTimer:id=>{w(id).timer={deadline:Date.now()+(w(id).timebox||settings().minutesPerProblem)*60000,fired:false};commit(id);render();tick();},
    unclear:id=>{queueRepair(id,'confidence');toast('Scheduled for revision tomorrow. Write down the part you cannot explain.');render();},
    stop:()=>{controller?.abort();clearInterval(playTimer);playTimer=null;},
    move:delta=>{step=Math.max(0,Math.min((trace?.result.steps?.length||1)-1,step+delta));paintTrace();},seek:value=>{step=Number(value);paintTrace();},play:()=>{if(playTimer){clearInterval(playTimer);playTimer=null;return;}playTimer=setInterval(()=>{if(!trace||step>=trace.result.steps.length-1||!document.getElementById('trace-body')){clearInterval(playTimer);playTimer=null;return;}step++;paintTrace();},650);},
    openBook:file=>{if(!file||file.size>100000000){toast('Choose a PDF smaller than 100 MB.');return;}if(pdfURL)URL.revokeObjectURL(pdfURL);pdfURL=URL.createObjectURL(file);modal(modalHead('Your C book')+`<iframe class="tutor-frame" title="Your locally opened C book" src="${pdfURL}"></iframe>`);document.querySelector('.modal')?.classList.add('wide-modal');},
    curriculum,demos,tick};
  ForgeStudy.allProblems().forEach(enrich);setInterval(tick,1000);render();
})();
