// Classic-script extension: uses Forge's existing state, dialogs, navigation,
// backup, and recall functions. No credentials are written to persistent state.
(() => {
  const curriculum=JSON.parse(document.getElementById('native-curriculum').textContent);
  const fullHTML=document.getElementById('stl-article').innerHTML;
  const all=curriculum.modules.flatMap(m=>m.lessons.map(l=>({...l,moduleId:m.id,moduleTitle:m.title})));
  const get=id=>all.find(l=>l.id===id);
  const C_START='#include <stdio.h>\nint main(void) {\n    long long a, b;\n    if (scanf("%lld %lld", &a, &b) != 2) return 0;\n    printf("%lld\\n", a + b);\n    return 0;\n}\n';
  const CPP_START='#include <iostream>\nint main() {\n    std::ios::sync_with_stdio(false);\n    std::cin.tie(nullptr);\n    long long a, b;\n    if (!(std::cin >> a >> b)) return 0;\n    std::cout << a + b << \'\\n\';\n}\n';
  let availableLanguages=[];
  let executionToken='',connectedBase='',connected=false,pollController=null,nativeBusy=false,lastNativeOutput='',moduleFilter='all';
  const original={render,labView,learnView,loadLab,validate,settingsView,resourcesView};
  function nativeDefaults(){return {language:'python',apiUrl:'',drafts:{c:{source:C_START,stdin:'7 12\n'},cpp:{source:CPP_START,stdin:'7 12\n'}},progress:{}};}
  function checkNative(n){
    if(!n||!['python','c','cpp'].includes(n.language)||typeof n.apiUrl!=='string'||n.apiUrl.length>500||!n.drafts||!n.progress||Array.isArray(n.progress))throw Error('Invalid C/C++ learning data.');
    if(n.apiUrl&&!validServiceURL(n.apiUrl))throw Error('Invalid compiler service URL in backup.');
    for(const lang of ['c','cpp']){const d=n.drafts[lang];if(!d||typeof d.source!=='string'||typeof d.stdin!=='string'||d.source.length>100000||d.stdin.length>50000)throw Error('Invalid native code draft.');}
    for(const [id,p] of Object.entries(n.progress)){if(!get(id)||!p||!Array.isArray(p.passed)||p.passed.some(i=>i!==0&&i!==1)||new Set(p.passed).size!==p.passed.length||!Number.isFinite(p.completedAt)||p.completedAt<0)throw Error('Invalid native lesson progress.');}
    // No imported auth field is ever consumed; only these fields are retained.
    return {language:n.language,apiUrl:n.apiUrl,drafts:{c:{source:n.drafts.c.source,stdin:n.drafts.c.stdin},cpp:{source:n.drafts.cpp.source,stdin:n.drafts.cpp.stdin}},progress:n.progress};
  }
  function ns(){if(!state.native)state.native=nativeDefaults();return state.native;}
  function validServiceURL(s){try{const u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash;}catch{return false;}}
  validate=function(s){original.validate(s);if(s.native)s.native=checkNative(s.native);return s;};
  try{if(state.native)state.native=checkNative(state.native);}catch{state.native=nativeDefaults();toast('C/C++ settings were reset because they were invalid. Your Python progress is unchanged.');}
  const completed=id=>!!ns().progress[id]?.completedAt;
  const unlocked=l=>l.prerequisites.every(completed);
  const tabs=active=>`<div class="language-tabs" aria-label="Learning tracks">${[['python','Python','#learn'],['c','C foundations','#native/c'],['cpp','C++ foundations','#native/cpp'],['atlas','Algorithm atlas','#native/atlas']].map(([id,label,href])=>`<a href="${href}" class="btn ${id===active?'primary':''}" ${id===active?'aria-current="page"':''}>${label}</a>`).join('')}</div>`;
  learnView=function(){return tabs('python')+original.learnView();};
  loadLab=function(id){ns().language='python';original.loadLab(id);};
  function languageBar(){return `<div class="language-bar card pad"><div><label for="lab-language"><b>Programming language</b></label><p class="small muted">Keep a separate draft for each language.</p></div><select id="lab-language" onchange="ForgeNative.changeLanguage(this.value)">${[['python','Python 3 · in your browser'],['c','C17 · isolated compiler'],['cpp','C++17 · isolated compiler']].map(([id,label])=>`<option value="${id}" ${ns().language===id?'selected':''}>${label}</option>`).join('')}</select><a class="btn small" href="#native/cpp">Learn C / C++ ${icon('arrow',13)}</a></div>`;}
  labView=function(){
    if(ns().language==='python')return languageBar()+original.labView();
    const lang=ns().language,draft=ns().drafts[lang];
    return languageBar()+pageHead('THE COMPILED LANGUAGE LAB',lang==='c'?'Think in C. Run with limits.':'Build your C++ toolkit.','Compile errors, program output, and runtime verdicts appear separately. Each run uses an isolated execution service.',`<button class="btn" onclick="ForgeNative.downloadCode()">Download .${lang==='c'?'c':'cpp'} ${icon('download',14)}</button>`)+
    `<div class="banner ${connected?'':'warn'}">${connected?'Compiler service connected. Code and input are sent to your configured service when you choose Compile & run.':'C/C++ compilation needs a connected execution service. You can study, edit, and download code now.'} <button class="textbtn" onclick="ForgeNative.connectDialog()">${connected?'Connection settings':'Connect compiler service'} ${icon('arrow',13)}</button></div>
    <div class="grid cols"><div><div class="codehead"><span>main.${lang==='c'?'c':'cpp'} · ${lang==='c'?'C17':'C++17'}</span><span>Syntax highlighting · Tab = 4 spaces</span></div>
    <div class="native-editor"><pre id="native-highlight" aria-hidden="true"></pre><textarea id="native-source" wrap="off" spellcheck="false" autocapitalize="off" autocomplete="off" aria-label="${lang==='c'?'C':'C++'} source code editor" oninput="ForgeNative.saveDraft(this.value)" onscroll="ForgeNative.syncScroll()">${esc(draft.source)}</textarea></div>
    <div class="flex wrap" style="margin:15px 0"><button id="native-run" class="btn primary" onclick="ForgeNative.run()" ${!connected||nativeBusy?'disabled':''}>${nativeBusy?'Waiting…':'Compile & run'} ${icon('play',14)}</button><button class="btn" onclick="ForgeNative.stop()" ${!nativeBusy?'disabled':''}>Stop waiting</button><span class="small muted">2s CPU · 5s wall · 256 MiB memory</span></div>
    <div class="field"><label for="native-stdin">Standard input</label><textarea id="native-stdin" oninput="ForgeNative.saveStdin(this.value)" maxlength="16384">${esc(draft.stdin)}</textarea></div>
    <h3 style="margin:16px 0 9px">Compilation & execution</h3><pre id="native-output" class="output" aria-live="polite">${esc(lastNativeOutput||'Predict the result, then compile and run. Execution completion is not an accepted contest submission.')}</pre></div>
    <div><div class="card pad"><h2>Start with a small experiment</h2><ol class="list-clean"><li>Read two integers and print their sum.</li><li>Replace addition with multiplication and check the numeric range.</li><li>Introduce a missing semicolon; recognize a compile error.</li><li>Restore the code, then test zero and a boundary.</li></ol><button class="btn small" onclick="ForgeNative.openLesson('${lang==='c'?'c-start':'cpp-start'}')">Open the first lesson</button></div><div class="spacer"></div><div class="card pad"><h3>Your data and the runner</h3><p class="small muted" style="margin-top:10px">Your compiler access token stays in this tab’s memory and is excluded from backups. The source and input you run are processed by your execution service and its configured Judge0 provider.</p><p class="small muted">Stop waiting cancels browser polling. An already submitted job remains governed by the server and worker limits. The Python runner is separate and still runs in a browser worker.</p></div></div></div>`;
  };
  function highlight(source){
    const pattern=/(\/\/[^\n]*|\/\*[\s\S]*?\*\/|"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|^\s*#.*$|\b(?:int|long|short|unsigned|signed|char|double|float|bool|void|auto|const|constexpr|static|struct|class|public|private|return|if|else|for|while|do|break|continue|switch|case|default|using|namespace|template|typename|sizeof|nullptr|true|false|new|delete)\b|\b\d+(?:\.\d+)?(?:[uUlLfF]+)?\b)/gm;
    let out='',end=0;for(const m of source.matchAll(pattern)){out+=esc(source.slice(end,m.index));const v=m[0];const cls=/^\s*#/.test(v)?'directive':/^\//.test(v)?'comment':/^["']/.test(v)?'string':/^\d/.test(v)?'number':'keyword';out+=`<span class="syntax-${cls}">${esc(v)}</span>`;end=m.index+v.length;}return out+esc(source.slice(end))+'\n';
  }
  function syncScroll(){const a=$('#native-source'),p=$('#native-highlight');if(a&&p){p.scrollTop=a.scrollTop;p.scrollLeft=a.scrollLeft;}}
  function paintEditor(){const p=$('#native-highlight');if(p)p.innerHTML=highlight(ns().drafts[ns().language]?.source||'');syncScroll();}
  function saveDraft(value){ns().drafts[ns().language].source=value;paintEditor();save();}
  function saveStdin(value){ns().drafts[ns().language].stdin=value;save();}
  function stop(){if(pollController)pollController.abort();pollController=null;nativeBusy=false;lastNativeOutput='Stopped waiting in this tab. The submitted job still has server-enforced time and memory limits.';if(location.hash.startsWith('#lab'))render();}
  function changeLanguage(lang){if(!['python','c','cpp'].includes(lang))return;if(nativeBusy)stop();if(pythonBusy)stopPython();ns().language=lang;lastNativeOutput='';save();render();}
  function connectDialog(){modal(modalHead('Connect your compiler service')+`<form onsubmit="ForgeNative.connect(event)"><p class="small muted" style="margin-bottom:18px">Use the HTTPS address of the Forge execution API deployed from this repository. Enter its personal access token, not a Judge0 credential. The token is held only in this tab.</p><div class="field"><label for="service-url">Forge API address</label><input id="service-url" name="url" type="url" required value="${esc(ns().apiUrl)}" placeholder="https://compiler.example.com"></div><div class="field"><label for="service-token">Personal execution token</label><input id="service-token" name="token" type="password" required minlength="32" maxlength="256" autocomplete="off" placeholder="Token configured on your API server"></div><p class="small muted" style="margin-bottom:15px">Connecting sends the token to this address to check availability. Running C/C++ then sends your source and input to it. Only connect a service you trust.</p><div id="connect-feedback" class="feedback bad" aria-live="polite"></div><div class="flex wrap" style="margin-top:15px"><button class="btn primary">Connect</button>${connected?'<button type="button" class="btn" onclick="ForgeNative.disconnect()">Disconnect</button>':''}</div></form>`);}
  async function fetchJSON(path,{method='GET',body,signal,base=connectedBase,token=executionToken}={}){
    const controller=new AbortController(),t=setTimeout(()=>controller.abort(),12000),abort=()=>controller.abort();signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)controller.abort();
    try{const r=await fetch(base+path,{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,signal:controller.signal,credentials:'omit',cache:'no-store',redirect:'error'});const d=await r.json();if(!r.ok)throw Error(d.message||'Execution API returned HTTP '+r.status);return d;}finally{clearTimeout(t);signal?.removeEventListener('abort',abort);}
  }
  async function connect(e){e.preventDefault();const f=new FormData(e.target),base=String(f.get('url')).trim().replace(/\/+$/,''),token=String(f.get('token')).trim(),feedback=$('#connect-feedback');
    if(!validServiceURL(base)||token.length<32){feedback.textContent='Use a valid HTTPS service URL and a token with at least 32 characters.';return;}
    const btn=e.target.querySelector('button');btn.disabled=true;feedback.textContent='Checking the execution service…';
    try{const d=await fetchJSON('/v1/languages',{base,token});if(!Array.isArray(d.languages)||!['c','cpp'].every(id=>d.languages.some(l=>l.id===id)))throw Error('The service must support C and C++.');availableLanguages=d.languages.filter(l=>/^(c|cpp|judge0-[1-9]\d{0,5})$/.test(l.id)).map(l=>({id:l.id,label:typeof l.label==='string'?l.label:l.id}));ns().apiUrl=base;executionToken=token;connectedBase=base;connected=true;save();closeModal();if(location.hash.startsWith('#problem/'))render();else go('lab');toast('Compiler service connected for this tab.');}catch(err){feedback.textContent=err.name==='AbortError'?'Connection timed out. Check the service address and deployment.':err.message;btn.disabled=false;}
  }
  function disconnect(){if(nativeBusy)stop();executionToken='';connectedBase='';connected=false;availableLanguages=[];closeModal();render();toast('Compiler disconnected. Its token was cleared from this tab.');}
  async function runNative(){
    if(connected&&ns().apiUrl!==connectedBase){disconnect();return;}
    if(nativeBusy||!connected){if(!connected)connectDialog();return;}
    const n=ns(),d=n.drafts[n.language],bytes=s=>new TextEncoder().encode(s).length;
    if(!d.source.trim()||bytes(d.source)>32768||bytes(d.stdin)>16384){toast('Use nonempty source up to 32 KiB and input up to 16 KiB.');return;}
    nativeBusy=true;pollController=new AbortController();const controller=pollController;lastNativeOutput='Submitting for isolated compilation…';render();
    try{let job=await fetchJSON('/v1/submissions',{method:'POST',body:{language:n.language,source:d.source,stdin:d.stdin},signal:controller.signal});const started=Date.now();
      while(!job.done){if(Date.now()-started>75000)throw Error('The service has not returned a result. Check the execution service; this is not a verdict on your algorithm.');await new Promise((resolve,reject)=>{const abort=()=>{clearTimeout(timer);reject(new DOMException('Stopped','AbortError'));};const timer=setTimeout(()=>{controller.signal.removeEventListener('abort',abort);resolve();},900);controller.signal.addEventListener('abort',abort,{once:true});if(controller.signal.aborted)abort();});job=await fetchJSON('/v1/submissions/'+encodeURIComponent(job.id),{signal:controller.signal});}
      lastNativeOutput=[`Status: ${job.status}`,job.compileOutput?'COMPILER\n'+job.compileOutput:'',job.stdout?'STDOUT\n'+job.stdout:'',job.stderr?'STDERR\n'+job.stderr:'',job.error||'',job.outputTruncated?'Output was truncated to the service limit.':'',job.timeSeconds!=null?`CPU: ${job.timeSeconds}s · Memory: ${job.memoryKb??'unknown'} KiB`:'',job.status==='completed'?'Execution completed. Compare the output with the expected answer.':''].filter(Boolean).join('\n\n');
    }catch(err){if(!controller.signal.aborted)lastNativeOutput=err.name==='AbortError'?'The request timed out. The worker still enforces the execution limits.':err.message;}
    finally{if(pollController===controller){nativeBusy=false;pollController=null;if(location.hash.startsWith('#lab'))render();}}
  }
  function nativeHome(track){const isAtlas=track==='atlas';let list=all.filter(l=>isAtlas?l.content_status==='blueprint':l.content_status==='complete'&&l.language===track);if(isAtlas&&moduleFilter!=='all')list=list.filter(l=>l.moduleId===moduleFilter);
    const heading=isAtlas?'The Algorithm Atlas.':track==='c'?'Learn C from the first line.':'C++ from first program to STL.';
    return tabs(track)+pageHead(isAtlas?'THE LONG-TERM MAP':'YOUR NEXT LANGUAGE',heading,isAtlas?'78 advanced study plans with prerequisites, correctness goals, complexities, pitfalls, and practice oracles. These are clearly labeled blueprints, not finished textbook chapters.':'Complete explanations, runnable examples, and recall checks. Keep Python as your main language while exploring, or choose C++ when you are ready to switch.')+
      `<div class="banner">${isAtlas?'Use this as a long-term reference. Your competition deadline is a reason to prioritize relevant foundations, not rush through every topic.':'C and C++ are independent tracks. Completing a lesson adds its cards to your existing spaced-review deck. Your Python progress stays intact.'}</div>`+
      (isAtlas?`<div class="filters"><select aria-label="Algorithm module" onchange="ForgeNative.filter(this.value)"><option value="all">All algorithm modules</option>${curriculum.modules.filter(m=>m.lessons.some(l=>l.content_status==='blueprint')).map(m=>`<option value="${m.id}" ${moduleFilter===m.id?'selected':''}>${esc(m.title)}</option>`).join('')}</select><a class="btn" href="content/curriculum.json" target="_blank" rel="noopener">Open complete curriculum JSON ${icon('up',13)}</a></div>`:'')+
      `<div class="topicgrid">${list.map((l,i)=>`<article class="card topiccard"><div class="between"><span class="eyebrow muted" style="font-size:10px">${isAtlas?esc(l.moduleTitle):String(i+1).padStart(2,'0')}</span><span class="pill ${completed(l.id)?'green':''}">${isAtlas?'Blueprint':completed(l.id)?'Completed':unlocked(l)?'Ready':'Preview'}</span></div><h3 style="margin-top:18px">${esc(l.title)}</h3><p>${esc(l.objectives[0])}</p><p class="small muted" style="margin-top:10px">${l.estimated_minutes} min suggested · ${l.language==='c'?'C17':'C++17'}</p><button class="btn ${!isAtlas&&unlocked(l)?'primary':''}" onclick="ForgeNative.openLesson('${l.id}')">${isAtlas?'Explore study plan':'Open lesson'} ${icon('arrow',14)}</button></article>`).join('')}</div>`;
  }
  function nativeLesson(id){const l=get(id);if(!l)return nativeHome('cpp');const done=completed(id),missing=l.prerequisites.filter(p=>!completed(p));
    const pre=`<div class="flex wrap" style="margin-bottom:20px"><a class="btn small" href="#native/${l.content_status==='blueprint'?'atlas':l.language}">← Back to ${l.content_status==='blueprint'?'atlas':'track'}</a><span class="pill ${done?'green':''}">${l.content_status==='blueprint'?'Study blueprint':done?'Completed':'Full lesson'}</span></div>`;
    const head=pageHead(esc(l.moduleTitle),esc(l.title),l.objectives[0]);
    const prerequisites=missing.length?`<div class="banner ${l.content_status==='complete'?'warn':''}">Prerequisites: ${missing.map(p=>`<a href="#native/${p}">${esc(get(p)?.title||p)}</a>`).join(', ')}. ${l.content_status==='complete'?'Preview freely; complete these before recording this lesson.':'Use these links to trace the dependency path.'}</div>`:'';
    if(l.content_status==='blueprint')return pre+head+prerequisites+`<div class="grid cols"><div class="card pad"><h2>Build the idea in six steps</h2>${l.study_outline.map((s,i)=>`<div class="study-step"><span class="stepnum">0${i+1}</span><div><h3>${esc(s.step)}</h3><p class="muted" style="margin-top:6px">${esc(s.task)}</p></div></div>`).join('')}<h2 style="margin:25px 0 12px">Practice with a reference implementation</h2><p>${esc(l.practice.task)}</p><ol class="list-clean">${l.practice.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><div class="trap"><b>Key pitfall</b><br>${esc(l.common_pitfalls[0])}</div></div><div><div class="card pad"><h2>Complexity target</h2><p style="margin-top:15px"><b>Time</b><br>${esc(l.complexity.time)}</p><p><b>Extra space</b><br>${esc(l.complexity.extra_space)}</p></div><div class="spacer"></div><div class="card pad"><h3>Read the reference</h3><p class="small muted" style="margin:10px 0">This entry is a structured study plan. Follow the reference for the full advanced article.</p>${l.source_urls.map(u=>`<a class="quick-link" href="${esc(u)}" target="_blank" rel="noopener noreferrer">cp-algorithms reference ${icon('up',13)}</a>`).join('')}<button class="btn small" style="margin-top:14px" onclick="go('lab')">Try an implementation</button></div></div></div>`;
    const checks=ns().progress[id]?.passed||[];
    const content=l.markdown_path?`<div class="stl-article">${fullHTML}</div>`:`<h2>The idea, from scratch</h2>${l.body.map((p,i)=>`<div class="step"><span class="stepnum">0${i+1}</span><p>${esc(p)}</p></div>`).join('')}<h2>Read the program</h2><div class="codehead"><span>main.${l.language==='c'?'c':'cpp'}</span><button class="textbtn" onclick="ForgeNative.loadExample('${id}')">Try in the lab ${icon('up',13)}</button></div><pre>${esc(l.code)}</pre><div class="trace"><b>Expected output</b><br><code>${esc(l.expected_output)}</code><br>Explain how each line contributes, then change one input or value.</div>`;
    return pre+head+prerequisites+`<article class="card lesson-body">${content}<div class="flex wrap" style="margin:25px 0"><button class="btn primary" onclick="ForgeNative.loadExample('${id}')">Load ${l.markdown_path?'practice solution':'example'} in the ${l.language==='c'?'C':'C++'} lab ${icon('code',14)}</button>${l.markdown_path?'<a class="btn" href="content/cpp-stl-fast-io.md" target="_blank" rel="noopener">Complete Markdown lesson</a>':''}</div><h2>Close the lesson. Retrieve.</h2><p>These checks record lesson completion. Independent practice is still needed to establish application skill.</p>${l.checks.map((c,i)=>`<form class="check" onsubmit="ForgeNative.check(event,'${id}',${i})"><label for="native-answer-${i}">${i+1}. ${esc(c.q)}</label><input id="native-answer-${i}" name="answer" autocomplete="off" placeholder="Your answer…" ${missing.length?'disabled':''}><button class="btn small" ${missing.length?'disabled':''}>Check</button><div id="native-feedback-${i}" class="feedback ${checks.includes(i)?'good':''}" aria-live="polite">${checks.includes(i)?'✓ Previously correct. Retrieve it again.':''}</div></form>`).join('')}<button id="native-complete" class="btn primary" onclick="ForgeNative.complete('${id}')" ${missing.length||checks.length<l.checks.length?'disabled':''}>${done?'Finish revisit':'Complete lesson & add recall cards'} ${icon('cards',14)}</button></article>`;
  }
  function check(e,id,i){e.preventDefault();const l=get(id);if(!l||!unlocked(l))return;const val=String(new FormData(e.target).get('answer')).trim();if(!val)return;const p=ns().progress[id]||{passed:[],completedAt:0},c=l.checks[i],ok=c.answers.some(a=>normalize(a)===normalize(val));p.passed=p.passed.filter(x=>x!==i);if(ok)p.passed.push(i);else ensureCard('native-check-'+id+'-'+i,'custom','['+l.title+'] '+c.q,c.why);ns().progress[id]=p;touch();save();const f=$('#native-feedback-'+i);f.className='feedback '+(ok?'good':'bad');f.textContent=(ok?'✓ Correct. ':'Try again. ')+c.why;$('#native-complete').disabled=p.passed.length<l.checks.length;}
  function complete(id){const l=get(id),p=ns().progress[id];if(!l||l.content_status!=='complete'||!unlocked(l)||!p||p.passed.length!==l.checks.length)return;p.completedAt=p.completedAt||Date.now();l.recall_cards.forEach((c,i)=>{const cid='native-'+id+'-'+i;if(!state.cards.some(x=>x.id===cid))ensureCard(cid,'custom','['+(l.language==='c'?'C':'C++')+'] '+c.q,c.a);});touch();save();toast('Lesson saved. Its recall cards are ready in your review deck.');go('review');}
  function loadExample(id){const l=get(id);if(!l?.code)return;if(nativeBusy)stop();if(pythonBusy)stopPython();ns().language=l.language;ns().drafts[l.language]={source:l.code,stdin:l.stdin||''};lastNativeOutput='';save();go('lab');toast('Example loaded. Predict its output before running.');}
  settingsView=function(){return original.settingsView()+`<div class="spacer"></div><div class="card pad"><h2>C and C++ execution</h2><p class="muted" style="margin:10px 0 18px">The learning content is ready. Native code execution uses a separate authenticated service. Connection credentials stay in this tab and are not included in backups.</p><button class="btn primary" onclick="ForgeNative.connectDialog()">${connected?'Manage connection':'Connect compiler service'}</button></div>`;};
  resourcesView=function(){return original.resourcesView()+`<div class="spacer"></div><div class="card pad"><h2>C, C++ and advanced algorithms</h2><a class="quick-link" href="#native/cpp">C++ foundation lessons ${icon('arrow',13)}</a><a class="quick-link" href="#native/cpp-stl-fast-io">Complete STL and fast-I/O module ${icon('arrow',13)}</a><a class="quick-link" href="#native/atlas">Algorithm Atlas · 78 study plans ${icon('arrow',13)}</a><a class="quick-link" href="content/curriculum.json" target="_blank" rel="noopener">Comprehensive curriculum JSON ${icon('up',13)}</a><a class="quick-link" href="https://github.com/axsimarosmelos/forge/blob/main/ARCHITECTURE.md" target="_blank" rel="noopener">Execution architecture and deployment guide ${icon('up',13)}</a></div>`;};
  render=function(){if(connected&&ns().apiUrl!==connectedBase){if(pollController)pollController.abort();pollController=null;nativeBusy=false;executionToken='';connectedBase='';connected=false;availableLanguages=[];}const route=(location.hash.slice(1)||'today').split('/');if(route[0]==='native'){updateChrome();$('#crumb').textContent='C / C++ & Algorithms';$$('.navitem').forEach(e=>e.classList.toggle('active',e.dataset.nav==='learn'));$('#app').innerHTML=(['c','cpp','atlas'].includes(route[1])?nativeHome(route[1]):nativeLesson(route[1]||'cpp-start'))+footer();document.title='Forge · C / C++ & Algorithms';}else original.render();if(route[0]==='lab'&&ns().language!=='python')paintEditor();if(route[0]==='today'){const card=document.createElement('div');card.className='banner';card.innerHTML=`New in your studio: <a href="#native/c">C foundations</a> · <a href="#native/cpp">C++ foundations</a> · <a href="#native/cpp-stl-fast-io">STL & fast I/O</a> · <a href="#native/atlas">Algorithm atlas</a>. Choose one primary contest language while you build fluency.`;$('#app').prepend(card);}};
  document.addEventListener('keydown',e=>{if(e.key==='Tab'&&e.target.id==='native-source'){e.preventDefault();const t=e.target,a=t.selectionStart,b=t.selectionEnd;t.value=t.value.slice(0,a)+'    '+t.value.slice(b);t.selectionStart=t.selectionEnd=a+4;saveDraft(t.value);}});
  async function executeExternal(payload,signal){
    if(!connected||ns().apiUrl!==connectedBase)throw Error('Connect your compiler service first.');
    const base=connectedBase,token=executionToken;
    let job=await fetchJSON('/v1/submissions',{method:'POST',body:payload,signal,base,token});
    const started=Date.now();
    while(!job.done){
      if(signal?.aborted)throw new DOMException('Stopped','AbortError');
      if(Date.now()-started>75000)throw Error('Execution service deadline exceeded. This is not an algorithm time-limit verdict.');
      await new Promise((resolve,reject)=>{const abort=()=>{clearTimeout(timer);reject(new DOMException('Stopped','AbortError'));};const timer=setTimeout(()=>{signal?.removeEventListener('abort',abort);resolve();},900);signal?.addEventListener('abort',abort,{once:true});if(signal?.aborted)abort();});
      job=await fetchJSON('/v1/submissions/'+encodeURIComponent(job.id),{signal,base,token});
    }
    return job;
  }
  window.ForgeNative={languages:()=>availableLanguages.map(l=>({...l})),isConnected:()=>connected&&ns().apiUrl===connectedBase,execute:executeExternal,highlight,saveDraft,saveStdin,syncScroll,changeLanguage,connectDialog,connect,disconnect,run:runNative,stop,openLesson:id=>go('native/'+id),loadExample,check,complete,filter:id=>{moduleFilter=id;render();},downloadCode:()=>{const lang=ns().language;download('main.'+(lang==='c'?'c':'cpp'),ns().drafts[lang].source,'text/plain');}};
  render();
})();
