/* Forge practice library: official metadata, licensed explanations and personal workspaces. */
(() => {
  'use strict';
  const C=ForgeCatalogCore, refs=JSON.parse(document.getElementById('lesson-references').textContent).lessons;
  const briefs=JSON.parse(document.getElementById('problem-briefs').textContent);
  const nativeLessons=JSON.parse(document.getElementById('native-curriculum').textContent).modules.flatMap(m=>m.lessons);
  const manifest=JSON.parse(document.getElementById('catalog-manifest').textContent);
  const START={python:'# Write a small experiment, then print its result.\nprint(7 + 12)\n',c:'#include <stdio.h>\nint main(void) {\n    printf("%d\\n", 7 + 12);\n    return 0;\n}\n',cpp:'#include <iostream>\nint main() {\n    std::ios::sync_with_stdio(false);\n    std::cin.tie(nullptr);\n    std::cout << 7 + 12 << \'\\n\';\n}\n'};
  const previous={render,updateChrome,lessonView,settingsView,resourcesView,roadmapView,validate};
  let settings=()=>{if(!state.study)state.study=C.defaults(today());return state.study;};
  const catalogData=new Map(),catalogErrors=new Map(),pending=new Map(),editorials=new Map(),editorialErrors=new Map();
  const filters={platform:'all',query:'',level:'all',tag:'all',status:'all',video:false,explained:false,page:0};
  let runContext=null,resultByID=new Map(),selectedVideo=new Set(),openedEditorial=new Set(),searchTimer,mathPromise;
  validate=function(s){previous.validate(s);if(s.study)C.validate(s.study);return s;};
  try{if(state.study)C.validate(state.study);}catch{state.study=C.defaults(today());toast('The practice plan could not be read. Your earlier course progress is available.');}
  for(const lesson of LESSONS)if(refs[lesson.id]?.length)lesson.reference=refs[lesson.id][0].url;
  // Map the old starter-set IDs into stable platform IDs without rewriting old records.
  const legacyID=p=>p.platform==='LeetCode'?'lc-'+(p.number||''):p.code?.match(/^(\d+)([A-Za-z][A-Za-z0-9]*)$/)?'cf-'+p.code.replace(/^(\d+)(.*)$/,'$1-$2'):'';
  function allProblems(){return [...catalogData.values()].flatMap(x=>x.problems);}
  function problem(id){for(const catalog of catalogData.values()){const found=catalog.byID.get(id);if(found)return found;}return null;}
  function mergedAttempts(){
    const lookup=new Map(allProblems().filter(p=>p.platform==='LeetCode').map(p=>[p.url.replace(/\/$/,''),p.id]));
    const old=state.attempts.flatMap(a=>{const p=P(a.pid);if(!p)return [];const id=p.platform==='Codeforces'?legacyID(p):lookup.get(p.url.replace(/\/$/,''));if(!id)return [];const current=problem(id);return [{...a,pid:id,platform:p.platform,difficulty:p.level,rating:current?.rating??(p.platform==='Codeforces'?Number(p.level):null),note:a.note||''}];});
    return [...old,...settings().attempts].sort((a,b)=>a.at-b.at);
  }
  function accept(raw){const value=C.catalog(raw);if(window.ForgeLearning)value.problems.forEach(ForgeLearning.enrich);value.byID=new Map(value.problems.map(p=>[p.id,p]));catalogData.set(value.platform,value);catalogErrors.delete(value.platform);return value;}
  async function jsonFile(path,maximum=20000000){
    const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),25000);
    try{const response=await fetch(path,{signal:controller.signal,credentials:'omit',cache:'no-cache'});if(!response.ok)throw Error('HTTP '+response.status);const declared=Number(response.headers?.get?.('content-length')||0);if(declared>maximum)throw Error('File is too large.');const text=await response.text();if(text.length>maximum)throw Error('File exceeds the reader limit.');return JSON.parse(text);}finally{clearTimeout(timer);}
  }
  const fileFor={LeetCode:'leetcode',Codeforces:'codeforces',AtCoder:'atcoder'};
  async function loadCatalog(platform,force=false){
    if(pending.has(platform))return pending.get(platform);if(catalogData.has(platform)&&!force)return;
    const task=(async()=>{try{accept(await jsonFile('content/catalog/'+fileFor[platform]+'.json'));}catch(e){catalogErrors.set(platform,'Could not load this catalog ('+(e.name==='AbortError'?'request timed out':e.message)+'). Retry when connected.');}finally{pending.delete(platform);if(['practice','problem','roadmap','today','curriculum'].includes(location.hash.slice(1).split('/')[0]||'today'))render();}})();
    pending.set(platform,task);return task;
  }
  async function loadAll(){await Promise.all(C.platforms.map(p=>loadCatalog(p)));}
  function statusOf(id){const attempts=mergedAttempts().filter(a=>a.pid===id);return attempts.some(a=>a.outcome==='independent')?'independent':attempts.at(-1)?.outcome||'new';}
  function foundationReady(){const lang=settings().primaryLanguage;return lang==='python'?['if','loops','lists'].every(learned):lang==='c'?!!state.native?.progress['c-arrays']?.completedAt:!!state.native?.progress['cpp-sequences']?.completedAt;}
  function ready(p){if(!foundationReady())return false;if(settings().primaryLanguage==='python'&&p.platform==='LeetCode'&&!learned('functions'))return false;return true;}
  function budget(){return (state.checkins[today()]?.minutes??state.profile.minutes);}
  function recommended(){const picks=new Set(window.ForgeLearning?.currentIDs()||[]);return C.recommendations(allProblems(),mergedAttempts(),{premium:settings().premium,ready,now:Date.now()}).sort((a,b)=>Number(picks.has(b.problem.id))-Number(picks.has(a.problem.id)));}
  function dailyTasks(){
    const cap=Math.min(12,Math.max(0,Math.floor(Math.max(0,budget()-45-Math.min(20,dueCards().length*2))/settings().minutesPerProblem)));
    const pool=recommended(),selected=[],used=new Set();
    for(const due of window.ForgeLearning?.due()||[]){const p=problem(due.id);if(p&&selected.length<cap){selected.push({problem:p,reason:'Due for a delayed re-solve: '+due.reasons.map(r=>ForgeLearningCore.reasons[r]).join(', ')});used.add(p.id);}}
    for(let round=0;selected.length<cap&&round<12;round++)for(const platform of ['LeetCode','Codeforces','LeetCode','AtCoder']){
      if(selected.length>=cap)break;const item=pool.find(x=>x.problem.platform===platform&&!used.has(x.problem.id));if(item){used.add(item.problem.id);selected.push(item);}
    }return selected;
  }
  function levelText(p){return p.platform==='LeetCode'?p.difficulty:(p.rating==null?'Unrated':p.platform==='AtCoder'?'Est. '+p.rating:String(p.rating));}
  function platformPill(p){return `<span class="pill platform-${p.platform.toLowerCase()}">${p.platform}</span>`;}
  function badge(text,color=''){return `<span class="pill ${color}">${esc(text)}</span>`;}
  const link=(url,title)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(title)} ${icon('up',12)}</a>`;
  function referencePanel(id,language){const list=refs[id]||[];if(!list.length)return '';return `<section class="card pad lesson-sources"><div class="between wrap"><div><span class="eyebrow muted">READ · TRACE · RECALL</span><h2 style="margin-top:8px">References for this lesson</h2></div><button class="btn primary" onclick="ForgeStudy.visualizeLesson('${id}')">Visualize an example ${icon('play',14)}</button></div><div class="reference-list">${list.map(r=>`<div><b>${link(r.url,r.title)}</b><p class="small muted">${esc(r.publisher)} · ${esc(r.why)}</p></div>`).join('')}</div><p class="small muted">Python Tutor supports Python, C and C++. The visualizer opens inside Forge; small examples work best. Advanced library features may need a simpler example.</p></section>`;}
  lessonView=function(id){return previous.lessonView(id)+referencePanel(id,'python');};
  function displayTutor(code,language,stdin=''){
    if(code.length>20000){toast('Choose a smaller example under 20,000 characters to visualize.');return;}
    const embed=C.tutorURL(code,language,stdin,true),external=C.tutorURL(code,language,stdin);
    modal(modalHead('Trace one step at a time')+`<p class="small muted">This embedded Python Tutor session sends the selected code and input to Python Tutor. Predict a line, step once, then explain how memory changed.</p><iframe class="tutor-frame" title="Python Tutor code visualization" src="${esc(embed)}" sandbox="allow-scripts allow-same-origin allow-forms" referrerpolicy="no-referrer"></iframe><div class="between wrap"><span class="small muted">If your browser blocks the frame, use the direct visualizer.</span>${link(external,'Open Python Tutor')}</div>`);
    document.querySelector('.modal')?.classList.add('wide-modal');
  }
  function visualizeLesson(id){const lesson=L(id)||nativeLessons.find(l=>l.id===id),language=L(id)?'python':lesson?.language||'cpp';if(lesson?.code){displayTutor(lesson.code,language,lesson.stdin||(id==='input'?'4 9\n':''));}else{displayTutor(START[language],language);}}
  function labVisualization(){const lang=state.native?.language||'python';displayTutor(lang==='python'?state.lab.code:state.native.drafts[lang].source,lang,lang==='python'?state.lab.stdin:state.native.drafts[lang].stdin);}
  function libraryView(){
    const all=allProblems(),attempts=mergedAttempts(),cf=C.level(attempts,'Codeforces'),at=C.level(attempts,'AtCoder');
    const summaries=C.platforms.map(p=>{const data=catalogData.get(p),count=data?.problems.length??manifest.catalogs[fileFor[p]]?.count??0;return `<button class="card catalog-platform ${filters.platform===p?'selected':''}" onclick="ForgeStudy.setFilter('platform','${p}')"><span class="eyebrow muted">${p}</span><strong>${count.toLocaleString()}</strong><span class="small muted">${data?'indexed tasks':pending.has(p)?'loading…':'snapshot tasks'} · ${C.solved(attempts,p).size} independent</span></button>`;}).join('');
    return pageHead('YOUR COMPLETE PRACTICE SHELF','One workspace. Three arenas.','Browse every task in the loaded snapshots. Study explanations, watch selected videos, keep notes and test your own code here.',`<button class="btn" onclick="ForgeStudy.reload()">Reload catalog snapshots</button>`)+
    `<div class="catalog-platforms">${summaries}</div><div class="between wrap catalog-band"><span>Practice bands: <b>Codeforces ${cf.rating}–${cf.rating+200}</b> · <b>AtCoder ${at.rating}–${at.rating+200} estimated</b></span><a class="textbtn" href="#roadmap">Your four-month plan ${icon('arrow',13)}</a></div>`+
    `<div class="catalog-toolbar card pad"><label class="search-field">Search title, ID or topic<input id="catalog-search" type="search" value="${esc(filters.query)}" placeholder="Two Sum, 4A, prefix sums…" oninput="ForgeStudy.search(this.value)"></label><div class="catalog-filter-row"><select aria-label="Platform" onchange="ForgeStudy.setFilter('platform',this.value)"><option value="all">All platforms</option>${C.platforms.map(p=>`<option ${filters.platform===p?'selected':''}>${p}</option>`).join('')}</select><select aria-label="Difficulty" onchange="ForgeStudy.setFilter('level',this.value)">${[['all','All difficulties'],['adaptive','My practice band'],['Easy','LeetCode Easy'],['Medium','LeetCode Medium'],['Hard','LeetCode Hard'],['low','Rated up to 1000'],['middle','Rated 1001–1800'],['high','Rated above 1800'],['unrated','Unrated']].map(([v,t])=>`<option value="${v}" ${filters.level===v?'selected':''}>${t}</option>`).join('')}</select><select aria-label="Progress status" onchange="ForgeStudy.setFilter('status',this.value)">${[['all','Any progress'],['new','Not attempted'],['independent','Solved independently'],['repair','Needs a revisit']].map(([v,t])=>`<option value="${v}" ${filters.status===v?'selected':''}>${t}</option>`).join('')}</select><label class="inline-check"><input type="checkbox" ${filters.video?'checked':''} onchange="ForgeStudy.setFilter('video',this.checked)"> Has a selected video</label><label class="inline-check"><input type="checkbox" ${filters.explained?'checked':''} onchange="ForgeStudy.setFilter('explained',this.checked)"> Has a community solution</label></div></div><div id="catalog-results"></div>`+
    `<details class="card pad catalog-sources"><summary>Catalog coverage and sources</summary>${C.platforms.map(p=>{const d=catalogData.get(p)||manifest.catalogs[fileFor[p]];return `<p class="small"><b>${p}</b> · ${esc(d?.fetchedAt?.slice(0,10)||'loading')}<br>${esc(d?.coverage||'No snapshot loaded.')}</p>`;}).join('')}<p class="small muted">Task metadata, community solutions and official statements are separate. Full platform statements and hidden tests are not mirrored. ${link('https://github.com/axsimarosmelos/forge/blob/main/content/catalog/NOTICE.md','Source credits and licenses')}</p></details>`;
  }
  function renderCatalogRows(){const target=$('#catalog-results');if(!target)return;const attempts=mergedAttempts(),prior=C.latest(attempts),solved=C.solved(attempts),cf=C.level(attempts,'Codeforces').rating,at=C.level(attempts,'AtCoder').rating,lc=C.leetcodeLevel(attempts),rank={Easy:1,Medium:2,Hard:3};
    const query=filters.query.trim().toLowerCase();let rows=allProblems().filter(p=>{
      if(filters.platform!=='all'&&p.platform!==filters.platform)return false;
      if(query&&!`${p.title} ${p.id} ${p.number} ${p.contest||''} ${p.tags.join(' ')}`.toLowerCase().includes(query))return false;
      if(filters.video&&!p.video)return false;if(filters.explained&&!p.editorialBatch)return false;
      const a=prior.get(p.id);if(filters.status==='new'&&a)return false;if(filters.status==='independent'&&!solved.has(p.id))return false;if(filters.status==='repair'&&!settings().workspaces[p.id]?.review&&(!a||a.outcome==='independent'))return false;
      if(['Easy','Medium','Hard'].includes(filters.level))return p.platform==='LeetCode'&&p.difficulty===filters.level;
      if(filters.level==='unrated')return p.platform!=='LeetCode'&&p.rating==null;
      if(filters.level==='low')return p.rating!=null&&p.rating<=1000;if(filters.level==='middle')return p.rating>1000&&p.rating<=1800;if(filters.level==='high')return p.rating>1800;
      if(filters.level==='adaptive')return p.platform==='LeetCode'?(rank[p.difficulty]||4)<=lc:p.rating!=null&&p.rating>=(p.platform==='Codeforces'?cf:at)-100&&p.rating<=(p.platform==='Codeforces'?cf:at)+200;
      return true;
    });
    rows.sort((a,b)=>C.platforms.indexOf(a.platform)-C.platforms.indexOf(b.platform)||(a.platform==='LeetCode'?Number(a.number)-Number(b.number):(a.rating??99999)-(b.rating??99999))||a.title.localeCompare(b.title));
    const size=30,pages=Math.max(1,Math.ceil(rows.length/size));filters.page=Math.min(filters.page,pages-1);const shown=rows.slice(filters.page*size,(filters.page+1)*size);
    target.innerHTML=`${[...catalogErrors].map(([p,e])=>`<div class="banner warn">${esc(p+': '+e)} <button class="textbtn" onclick="ForgeStudy.retry('${p}')">Retry</button></div>`).join('')}<div class="between wrap results-count"><span>${rows.length.toLocaleString()} matching tasks${pending.size?' · loading more catalogs…':''}</span><span class="small muted">${allProblems().filter(p=>p.video).length} selected video links · ${allProblems().filter(p=>p.editorialBatch).length} community solutions</span></div><div class="problem-list">${shown.map(p=>`<a class="problem-row" href="#problem/${p.id}"><span class="problem-number">${esc(String(p.number))}</span><div class="problem-row-main"><strong>${esc(p.title)}</strong><span class="small muted">${esc(p.tags.slice(0,3).join(' · ')||p.contest||p.kind)}${p.premium?' · Premium marker':''}${p.kind!=='algorithm'?' · '+p.kind.toUpperCase()+' track':''}</span></div><div class="problem-row-badges">${platformPill(p)}${badge(levelText(p))}${p.video?badge('Video','green'):''}${p.editorialBatch?badge('Solution'):''}${solved.has(p.id)?badge('Independent','green'):prior.has(p.id)?badge('Revisit'):''}</div><span class="problem-row-arrow">→</span></a>`).join('')||'<div class="card pad muted">'+(pending.size?'Loading the problem shelves…':'No tasks match these filters. Change the filters or retry a catalog that failed to load.')+'</div>'}</div><div class="between pagination"><button class="btn small" onclick="ForgeStudy.page(-1)" ${filters.page===0?'disabled':''}>← Previous</button><span>Page ${filters.page+1} of ${pages}</span><button class="btn small" onclick="ForgeStudy.page(1)" ${filters.page>=pages-1?'disabled':''}>Next →</button></div>`;
  }
  function setFilter(key,value){if(!Object.hasOwn(filters,key))return;filters[key]=value;filters.page=0;render();}
  function workspace(id){if(!C.safeID(id))throw Error('Invalid workspace ID');if(!settings().workspaces[id])settings().workspaces[id]={language:settings().primaryLanguage,drafts:{...START,javascript:'// Use readline() for one input line, or stdin for all input.\nconsole.log(7 + 12);\n'},statement:'',notes:'',stdin:'',expected:'',video:''};return settings().workspaces[id];}
  const dirtyWorkspace=id=>window.ForgeWorkspaceStorage?.touch(id);
  function updateWorkspace(id,key,value){const w=workspace(id);if(['statement','notes','stdin','expected'].includes(key)){w[key]=value.slice(0,key==='statement'?100000:50000);}else if(key==='code'){w.drafts[w.language]=value.slice(0,100000);paintProblemEditor(id);}dirtyWorkspace(id);save();}
  function paintProblemEditor(id){const e=$('#problem-highlight');if(e){const w=workspace(id);e.innerHTML=w.language==='python'?esc(w.drafts.python)+'\n':ForgeNative.highlight(w.drafts[w.language]);}syncProblemScroll();}
  function syncProblemScroll(){const input=$('#problem-code'),display=$('#problem-highlight');if(input&&display){display.scrollTop=input.scrollTop;display.scrollLeft=input.scrollLeft;}}
  function studyBrief(id){const b=briefs[id];if(!b)return '';return `<div class="study-brief"><span class="eyebrow green-text">FORGE STUDY BRIEF</span><p>${esc(b.summary)}</p><div class="grid two"><div><h3>Example input</h3><pre>${esc(b.exampleInput)}</pre></div><div><h3>Expected result</h3><pre>${esc(b.exampleOutput)}</pre></div></div><p class="small muted">${esc(b.authorship)}</p><details ontoggle="if(this.open)ForgeStudy.markHelp('${id}')"><summary>A nudge if you get stuck</summary><p>${esc(b.prompt)}</p></details></div>`;}
  function problemView(id){
    const p=problem(id);if(!p)return pageHead('PROBLEM WORKSPACE','Loading this task…','Your catalog is loading. If it is unavailable, retry it from the problem library.')+`<a class="btn" href="#practice">Open problem library</a>${[...catalogErrors].map(([platform,error])=>`<p class="small muted">${esc(platform+': '+error)}</p>`).join('')}`;
    const w=workspace(id),video=w.video||p.video?.id,history=mergedAttempts().filter(a=>a.pid===id),result=resultByID.get(id),busy=runContext?.id===id||window.ForgeLearning?.busy();
    const status=w.review?.due<=Date.now()?'Re-solve due':history.some(a=>a.outcome==='independent')?'Solved independently':history.length?'Revisit scheduled':'New task';
    return `<div class="between wrap"><a class="btn small" href="#practice">← Problem library</a><div class="flex wrap">${platformPill(p)}${badge(levelText(p))}${badge(status,status==='Solved independently'?'green':'')}${p.premium?badge('Premium marker'):''}</div></div>`+pageHead(esc(`${p.platform.toUpperCase()} / ${p.number}`),esc(p.title),'Read the task, attempt it, then reveal help. Your code and notes stay in this problem workspace.')+
    `<div class="problem-workspace"><div class="study-pane"><section class="card pad"><h2>Understand the task</h2>${studyBrief(id)}<p class="small muted" style="margin:12px 0">This workspace includes catalog metadata and licensed community help. Save your own task notes or a statement you are permitted to use below. Official statements and private judge tests are not copied here.</p><div class="flex wrap source-actions">${link(p.url,p.directUrlVerified===false?'Find official task by ID':'Official task')}${p.reference?link(p.reference,'Community source'):''}</div>${p.kind!=='algorithm'?`<div class="banner warn">This is a ${esc(p.kind.toUpperCase())} task. Select a compatible runtime below. SQL tasks also need a schema and data; platform function templates need a test driver.</div>`:''}<label class="field-label" for="task-notes">My task summary / permitted study text</label><textarea id="task-notes" class="statement-input" maxlength="100000" oninput="ForgeStudy.update('${id}','statement',this.value)" placeholder="Write the input, required output, constraints and one example in your own words.">${esc(w.statement)}</textarea><details class="attempt-routine"><summary>Before you code</summary><ol class="list-clean"><li>State exactly what one valid answer looks like.</li><li>Work a tiny example by hand.</li><li>Write a correct baseline and estimate its cost.</li><li>Identify what repeated work can be removed.</li><li>Test a boundary and an adversarial case.</li></ol></details></section>
    <section class="card pad"><div class="between wrap"><h2>Solution walkthrough</h2>${video?badge(w.video?'Your saved video':'Selected walkthrough','green'):badge('Video not selected yet')}</div><p class="small muted">Try independently before watching. Pause at the key idea and predict the next step.</p>${video?`<button class="btn" onclick="ForgeStudy.showVideo('${id}')">${selectedVideo.has(id)?'Reload video':'Watch inside Forge'} ${icon('play',14)}</button><div id="problem-video">${selectedVideo.has(id)?videoFrame(video):''}</div><p class="small muted">${w.video?'Personal selection.':esc(p.video.selection)} ${link('https://www.youtube.com/watch?v='+video,'YouTube link')}</p>`:`<p class="small muted">No verified problem-to-video mapping is available for this task yet.</p>${link('https://www.youtube.com/results?search_query='+encodeURIComponent(p.platform+' '+p.number+' '+p.title+' explanation'),'Search YouTube for this exact task')}`}<details><summary>Save a different YouTube walkthrough</summary><form onsubmit="ForgeStudy.saveVideo(event,'${id}')"><input name="video" type="url" required placeholder="https://www.youtube.com/watch?v=…"><button class="btn small">Save video link</button></form></details></section>
    <section class="card pad"><div class="between wrap"><h2>Read the explanation</h2>${p.editorialBatch?badge('Licensed community solution'):badge('Personal study notes')}</div><p class="small muted">Explain the approach yourself first. Revealing help makes this a guided attempt.</p>${p.editorialBatch?`<button class="btn primary" onclick="ForgeStudy.reveal('${id}')">${openedEditorial.has(id)?'Reload explanation':'Reveal community solution'} ${icon('book',14)}</button><div id="editorial-content">${openedEditorial.has(id)?editorialHTML(id):''}</div>`:`<p class="small muted">A licensed in-site editorial has not been added for this task. Use the topic references below and record your own derivation.</p>`}<div class="topic-reference-box">${topicReferences(p)}</div></section>
    <section class="card pad"><h2>Your reasoning and mistakes</h2><textarea class="notes-input" maxlength="50000" oninput="ForgeStudy.update('${id}','notes',this.value)" placeholder="Invariant, time/space complexity, failed idea, and the case that exposed it…">${esc(w.notes)}</textarea><button class="btn small" onclick="ForgeStudy.addRecall('${id}')">Turn this into a recall card</button></section></div>
    <div class="coding-pane">${window.ForgeLearning?.toolsPanel(id,w)||''}<section class="card pad editor-panel"><div class="between wrap"><h2>Your code</h2><select aria-label="Problem language" onchange="ForgeStudy.language('${id}',this.value)">${[['python','Python 3 · browser'],['javascript','JavaScript · browser'],['c','C17 · compiler'],['cpp','C++17 · compiler'],...ForgeNative.languages().filter(l=>!['c','cpp'].includes(l.id)).map(l=>[l.id,l.label]),...(/^judge0-/.test(w.language)&&!ForgeNative.languages().some(l=>l.id===w.language)?[[w.language,'Saved compiler language · reconnect']]:[])].map(([lang,label])=>`<option value="${lang}" ${w.language===lang?'selected':''}>${label}</option>`).join('')}</select></div><div class="codehead"><span>${esc(p.id)}.${w.language==='python'?'py':w.language==='c'?'c':w.language==='cpp'?'cpp':w.language==='javascript'?'js':'txt'}</span><span>Tab = 4 spaces</span></div><div class="native-editor problem-editor"><pre id="problem-highlight" aria-hidden="true"></pre><textarea id="problem-code" wrap="off" spellcheck="false" autocapitalize="off" autocomplete="off" aria-label="Problem source code" oninput="ForgeStudy.update('${id}','code',this.value)" onscroll="ForgeStudy.syncScroll()">${esc(w.drafts[w.language])}</textarea></div><p class="small muted">Use a complete program for local testing. LeetCode method templates need imports, any node definitions, and a test call; C/C++ needs a main function.</p><div class="grid two"><div class="field"><label for="problem-stdin">Standard input</label><textarea id="problem-stdin" oninput="ForgeStudy.update('${id}','stdin',this.value)">${esc(w.stdin)}</textarea></div><div class="field"><label for="problem-expected">Expected output for this test</label><textarea id="problem-expected" oninput="ForgeStudy.update('${id}','expected',this.value)" placeholder="Optional: the answer you worked out">${esc(w.expected)}</textarea></div></div><div class="flex wrap"><button id="problem-run" class="btn primary" onclick="ForgeStudy.run('${id}')" ${busy?'disabled':''}>${busy?'Running…':'Run my test'} ${icon('play',14)}</button><button class="btn" onclick="ForgeStudy.stop()" ${!busy?'disabled':''}>Stop</button><button class="btn" onclick="ForgeStudy.visualizeProblem('${id}')">Visualize</button><button class="btn small" onclick="ForgeStudy.download('${id}')">Download</button></div>${!['python','javascript'].includes(w.language)&&!ForgeNative.isConnected()?'<p class="small muted">Native execution needs your hosted compiler service. <button class="textbtn" onclick="ForgeNative.connectDialog()">Connect compiler</button></p>':''}<pre id="problem-output" class="output" aria-live="polite">${esc(result||'Predict the output, then run. This checks your chosen input, not the platform’s hidden tests.')}</pre></section>
    <section class="card pad"><h2>Record the outcome</h2><p class="small muted">This is your reported learning outcome. An output match does not automatically mark the problem solved.</p><form onsubmit="ForgeStudy.log(event,'${id}')"><div class="field"><label for="attempt-outcome">How did the attempt go?</label><select id="attempt-outcome" name="outcome"><option value="independent">Solved independently</option><option value="hinted">Solved with help / watched a solution</option><option value="stuck">Still stuck</option></select></div><div class="field"><label for="attempt-confidence">Can you explain why it works?</label><select id="attempt-confidence" name="confidence"><option value="clear">Yes, including correctness and complexity</option><option value="partial">Only partly</option><option value="lost">Not yet</option></select></div><div class="field"><label for="attempt-minutes">Minutes spent</label><input id="attempt-minutes" name="minutes" type="number" min="1" max="600" value="25" required></div><div class="field"><label for="attempt-lesson">One lesson for next time</label><textarea id="attempt-lesson" name="note" maxlength="10000" placeholder="What made the idea correct? What will you test next time?"></textarea></div><button class="btn primary">Save attempt & adapt my plan</button></form>${history.length?`<div class="attempt-history">${history.slice(-5).reverse().map(a=>`<p class="small"><b>${esc(a.outcome)}</b> · ${a.minutes} min · ${new Date(a.at).toLocaleDateString()}<br>${esc(a.note||'')}</p>`).join('')}</div>`:''}</section></div></div>`;
  }
  function videoFrame(id){return `<iframe class="solution-video" src="https://www.youtube-nocookie.com/embed/${id}" title="Problem solution video" loading="lazy" allow="encrypted-media; picture-in-picture; fullscreen" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe>`;}
  function markHelp(id){workspace(id).helpAt=Date.now();dirtyWorkspace(id);save();}
  function showVideo(id){const p=problem(id),video=workspace(id).video||p?.video?.id;if(!video)return;workspace(id).helpAt=Date.now();dirtyWorkspace(id);save();selectedVideo.add(id);$('#problem-video').innerHTML=videoFrame(video);}
  function saveVideo(event,id){event.preventDefault();const idValue=C.videoID(String(new FormData(event.target).get('video')));if(!idValue){toast('Use a valid HTTPS YouTube video link.');return;}workspace(id).video=idValue;dirtyWorkspace(id);save();render();}
  function topicReferences(p){
    const tags=p.tags.join(' ').toLowerCase();const choices=[['binary search','binary'],['prefix','prefix'],['two pointers','twopointers'],['sliding window','window'],['dynamic programming','dp'],[' dp','dp'],['graph','bfs'],['breadth','bfs'],['depth','dfs'],['heap','heap'],['stack','stack'],['sort','sorting'],['hash','counting'],['string','strings'],['math','math'],['greedy','greedy'],['tree','tree-dp']];
    const keys=[...new Set(choices.filter(([tag])=>tags.includes(tag)).map(([,id])=>id))].slice(0,3);if(!keys.length)keys.push(p.kind==='algorithm'?'complexity':'functions');
    return `<h3>Refresh the relevant concepts</h3>${keys.map(id=>`<a class="quick-link" href="#${L(id)?'learn':'native'}/${id}">${esc(L(id)?.title||nativeLessons.find(l=>l.id===id)?.title||id)} ${icon('arrow',13)}</a>`).join('')}`;
  }
  function proseHTML(text){
    // Treat every character as text first. Only a small Markdown subset is rendered.
    const inline=s=>esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\$([^$\n]+)\$/g,(_m,math)=>`<span class="math-inline" data-math="${math.replaceAll('"','&quot;')}">${math}</span>`);
    let code=false,buffer=[],output=[];
    for(const line of String(text).split('\n')){
      if(line.trim().startsWith('```')){if(code){output.push('<pre>'+esc(buffer.join('\n'))+'</pre>');buffer=[];}code=!code;continue;}
      if(code){buffer.push(line);continue;}
      if(/^#{1,6}\s/.test(line)){output.push('<h3>'+inline(line.replace(/^#+\s*/,''))+'</h3>');continue;}
      if(/^\s*>/.test(line)){output.push('<p class="thinking-line">'+inline(line.replace(/^\s*>\s?/,''))+'</p>');continue;}
      if(/^\s*[-*]\s/.test(line)){output.push('<p class="editorial-list-item">• '+inline(line.replace(/^\s*[-*]\s*/,''))+'</p>');continue;}
      output.push(line.trim()?'<p>'+inline(line)+'</p>':'');
    }
    if(buffer.length)output.push('<pre>'+esc(buffer.join('\n'))+'</pre>');return output.join('');
  }
  function loadMath(){
    if(window.katex){paintMath();return;}
    if(mathPromise)return;
    mathPromise=new Promise(resolve=>{const css=document.createElement('link');css.rel='stylesheet';css.href='https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.css';document.head.appendChild(css);const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/katex@0.16.22/dist/katex.min.js';script.onload=resolve;script.onerror=resolve;document.head.appendChild(script);}).then(paintMath);
  }
  function paintMath(){if(!window.katex)return;document.querySelectorAll('[data-math]').forEach(e=>{try{window.katex.render(e.dataset.math,e,{throwOnError:false,trust:false,strict:'ignore'});}catch{/* Plain math stays readable if rendering fails. */}});}
  function templateLanguage(label){const local={Python3:'python',Python:'python','C++':'cpp',C:'c',JavaScript:'javascript'};if(local[label])return local[label];return ForgeNative.languages().find(l=>l.label.split(' (')[0]===label)?.id||'';}
  function editorialHTML(id){
    if(editorialErrors.has(id))return `<p class="small muted">${esc(editorialErrors.get(id))}</p>`;
    const item=editorials.get(id);if(!item)return '<p class="small muted">Loading the community solution…</p>';
    const valid=item.solutions?.filter(s=>s.codes?.some(c=>c.code.trim())||s.explanation.replace(/^#+[^\n]*/gm,'').trim().length>=30)||[];
    if(!valid.length)return '<p class="small muted">This source currently contains a placeholder. A complete explanation has not been added yet.</p>';
    return `<div class="editorial-body">${valid.map((s,i)=>`<section>${proseHTML(s.explanation)}${s.codes.filter(c=>c.code.trim()).map((code,j)=>`<details class="template-details"><summary>${esc(code.language)} template</summary><pre>${esc(code.code)}</pre>${!!templateLanguage(code.language)?`<button class="btn small" onclick="ForgeStudy.loadTemplate('${id}',${i},${j})">Load into my editor</button>`:''}</details>`).join('')}</section>`).join('')}<div class="editorial-attribution"><b>${esc(item.author)}</b> · ${link(item.licenseUrl,item.license)}<br>${link(item.sourceUrl,'Exact source and contributors')}<p>${esc(item.adaptation)}</p></div></div>`;
  }
  async function reveal(id){
    const p=problem(id);if(!p?.editorialBatch)return;workspace(id).helpAt=Date.now();dirtyWorkspace(id);save();openedEditorial.add(id);editorialErrors.delete(id);
    const target=$('#editorial-content');if(target)target.innerHTML=editorialHTML(id);
    if(!editorials.has(id))try{const batch=await jsonFile('content/editorials/lc-'+p.editorialBatch+'.json',5000000);for(const [key,value] of Object.entries(batch)){if(C.safeID(key)&&value.id===key&&Array.isArray(value.solutions)&&value.license==='CC-BY-SA-4.0'&&C.safeURL(value.sourceUrl,['github.com'])&&value.licenseUrl==='https://creativecommons.org/licenses/by-sa/4.0/')editorials.set(key,value);}if(!editorials.has(id))throw Error('This solution is unavailable in the current source snapshot.');}catch(e){editorialErrors.set(id,'Could not load the explanation. '+e.message);}
    if(location.hash==='#problem/'+id){$('#editorial-content').innerHTML=editorialHTML(id);loadMath();}
  }
  function loadTemplate(id,solutionIndex,codeIndex){const item=editorials.get(id);const valid=item?.solutions.filter(s=>s.codes?.some(c=>c.code.trim())||s.explanation.replace(/^#+[^\n]*/gm,'').trim().length>=30);const code=valid?.[solutionIndex]?.codes.filter(c=>c.code.trim())[codeIndex];if(!code)return;const language=templateLanguage(code.language);if(!language)return;
    const w=workspace(id);w.language=language;w.helpAt=Date.now();w.drafts[language]=code.code;dirtyWorkspace(id);save();render();toast('Template loaded. Add the required imports, node types and test driver before running locally.');
  }
  function addRecall(id){const p=problem(id),w=workspace(id);modal(modalHead('Remember the reasoning')+`<form onsubmit="ForgeStudy.saveRecall(event,'${id}')"><div class="field"><label>Recall question</label><input name="q" required maxlength="2000" value="${esc('How would I solve '+p.title+'? State the invariant and complexity.')}" /></div><div class="field"><label>Answer in your own words</label><textarea name="a" required maxlength="5000">${esc(w.notes.slice(0,5000))}</textarea></div><button class="btn primary">Add to Review</button></form>`);}
  function saveRecall(event,id){event.preventDefault();const f=new FormData(event.target),q=String(f.get('q')).trim(),a=String(f.get('a')).trim();if(!q||!a)return;ensureCard('study-'+id+'-'+Date.now(),'custom',q,a);save();closeModal();toast('Your recall card is ready in Review.');}
  function log(event,id){event.preventDefault();const p=problem(id),w=workspace(id),f=new FormData(event.target);let outcome=String(f.get('outcome')),minutes=Number(f.get('minutes')),note=String(f.get('note')).trim();if(!['independent','hinted','stuck'].includes(outcome)||!Number.isFinite(minutes)||minutes<1||minutes>600||note.length>10000){toast('Check the outcome, time and note.');return;}
    const last=settings().attempts.filter(a=>a.pid===id).at(-1)?.at||0,usedHelp=(w.helpAt||0)>last;if(outcome==='independent'&&usedHelp)outcome='hinted';
    const confidence=String(f.get('confidence')||'clear');if(!['clear','partial','lost'].includes(confidence))return;if(confidence!=='clear'&&outcome==='independent')outcome='hinted';
    const attempt={pid:id,platform:p.platform,outcome,minutes,note,at:Date.now(),difficulty:p.difficulty,rating:p.rating??null};settings().attempts.push(attempt);window.ForgeLearning?.recorded(id,attempt,confidence);
    if(outcome!=='independent')ensureCard('study-repair-'+id,'custom','Rebuild '+p.title+' without the solution.',note||'State the input and output, derive the invariant, explain the complexity, and test a boundary.',Date.now()+86400000);
    touch();save();render();toast(usedHelp&&String(f.get('outcome'))==='independent'?'Saved as a guided attempt because help was revealed. Revisit later without help.':'Attempt saved. Your next recommendations have been updated.');
  }
  function stopRun(){if(!runContext)return;const ctx=runContext;ctx.worker?.terminate();ctx.abort.abort();clearTimeout(ctx.timer);runContext=null;resultByID.set(ctx.id,['python','javascript'].includes(ctx.language)?'Browser execution stopped.':'Stopped waiting. The native worker still enforces its limits.');if(location.hash==='#problem/'+ctx.id)render();}
  async function runProblem(id){const p=problem(id),w=workspace(id);if(runContext||window.ForgeLearning?.busy()){toast('Stop the current test before starting another.');return;}
    const bytes=s=>new TextEncoder().encode(s).length;if(!w.drafts[w.language].trim()||bytes(w.drafts[w.language])>32768||bytes(w.stdin)>16384){toast('Use source up to 32 KiB and input up to 16 KiB.');return;}
    if(!['python','javascript'].includes(w.language)&&!ForgeNative.isConnected()){ForgeNative.connectDialog();return;}
    const ctx={id,language:w.language,abort:new AbortController(),worker:null,timer:null};runContext=ctx;const expected=w.expected;resultByID.set(id,'Loading the runtime or running your test…');render();
    try{const result=await ForgeRunner.execute({language:w.language,source:w.drafts[w.language],stdin:w.stdin},ctx.abort.signal);if(runContext!==ctx)return;
      const normalized=s=>s.replace(/\r\n/g,'\n').replace(/\n$/,'');const comparison=expected&&result.status==='completed'?(normalized(result.stdout||'')===normalized(expected)?'Your chosen test output matches.':'Your chosen test output differs.'):'';
      const check=ForgeLearningCore.compare(result,expected,expected!=='');if(check.reason)window.ForgeLearning?.queueRepair(id,check.reason);
      resultByID.set(id,[`Status: ${result.status}`,result.compileOutput?'COMPILER\n'+result.compileOutput:'',result.stdout?'STDOUT\n'+result.stdout:'',result.stderr?'STDERR\n'+result.stderr:'',result.error||'',comparison,'Local test only. Official acceptance is not checked or recorded automatically.'].filter(Boolean).join('\n\n'));
    }catch(e){if(runContext===ctx)resultByID.set(id,e.message);}finally{if(runContext===ctx){clearTimeout(ctx.timer);runContext=null;if(location.hash==='#problem/'+id)render();}}
  }
  function phaseLinks(ids){return ids.map(id=>`<a class="pill" href="#${L(id)?'learn':'native'}/${id}">${esc(L(id)?.title||nativeLessons.find(l=>l.id===id)?.title||id)}</a>`).join('');}
  function nextLanguageLesson(){if(settings().primaryLanguage==='python')return {id:nextLesson().lesson.id,route:'learn',title:nextLesson().lesson.title};const next=nativeLessons.find(l=>l.content_status==='complete'&&l.language===settings().primaryLanguage&&!state.native?.progress[l.id]?.completedAt&&l.prerequisites.every(id=>state.native?.progress[id]?.completedAt));return next?{id:next.id,route:'native',title:next.title}:null;}
  function planView(){
    const s=settings(),loaded=catalogData.has('LeetCode'),p=loaded?C.pace(s,allProblems(),mergedAttempts(),today(),budget()):null,items=dailyTasks(),next=nextLanguageLesson();
    return `<div class="language-tabs"><a class="btn primary" href="#roadmap">Four-month learning plan</a><a class="btn" href="#curriculum">Chapter-by-chapter curriculum</a></div>`+pageHead('YOUR FOUR-MONTH CAMPAIGN','A clear goal. A plan that adapts.',`${s.start} → ${s.end}. Follow the sixteen study blocks, build contest skill and revisit mistakes. The full archive remains available for extra practice.`, '<button class="btn" onclick="ForgeStudy.planSettings()">Edit plan</button>')+
    `<p><a class="btn primary" href="#curriculum">Open the 16-block curriculum →</a></p>${window.ForgeLearning?.nextBook()||''}<details class="card pad"><summary>Optional full-archive LeetCode pace estimate</summary><div class="plan-metrics"><div class="card pad"><span class="eyebrow muted">LEETCODE PROGRESS</span><strong>${p?p.done.toLocaleString():'…'} <small>/ ${p?p.total.toLocaleString():manifest.catalogs.leetcode.count.toLocaleString()}</small></strong><span class="small muted">distinct independently solved tasks</span></div><div class="card pad"><span class="eyebrow muted">TIME REMAINING</span><strong>${p?p.left:C.days(today(),s.end)} <small>days</small></strong><span class="small muted">four calendar months from your start</span></div><div class="card pad"><span class="eyebrow muted">PACE NEEDED FOR THE GOAL</span><strong>${p?p.required===null?'Overdue':p.required:'…'} <small>${p?.required===null?'':'/ day'}</small></strong><span class="small muted">remaining tasks ÷ remaining days</span></div></div>`+
    (p?`<div class="banner ${p.requiredMinutes>budget()||p.required===null?'warn':''}">${p.required===null?'Your target date has passed. Extend the plan or narrow the goal to continue at a useful pace.':`At about ${p.estimate} minutes per independently solved task, the goal needs roughly ${p.requiredMinutes.toLocaleString()} minutes daily before lessons and reviews. Your current budget is ${budget()} minutes. ${p.requiredMinutes>budget()?'The required pace exceeds that budget; today’s queue stays within your available time.':'Use spare time for review and unfamiliar variations.'}`}</div><p class="small muted">${s.scope==='all'?`Your full-set goal includes ${p.otherLanguages} SQL/JavaScript/shell tasks and ${p.premium} tasks marked Premium by the source. These may need additional languages or platform access.`:'Your goal currently includes algorithm tasks only.'} Required pace is arithmetic, not a promise of mastery.</p>`:'<div class="banner">Loading the LeetCode catalog to calculate your pace…</div>')+
    `</details><div class="grid cols campaign-today"><div class="card pad"><h2>Today’s useful work</h2><p class="muted small">Review due cards, learn the next prerequisite, then attempt the tasks that fit your level and time.</p><div class="daily-learning-links"><a class="quick-link" href="#review">${dueCards().length} recall cards due ${icon('arrow',13)}</a>${next?`<a class="quick-link" href="#${next.route}/${next.id}">Next lesson: ${esc(next.title)} ${icon('arrow',13)}</a>`:''}</div>${!foundationReady()?'<p class="small muted">Complete your language’s conditions, loops and arrays lessons to unlock the daily problem queue. You can browse the full catalog now.</p>':''}${items.map(x=>`<a class="daily-task" href="#problem/${x.problem.id}"><span>${platformPill(x.problem)} ${badge(levelText(x.problem))}<b>${esc(x.problem.title)}</b><small>${esc(x.reason)}</small></span><span>→</span></a>`).join('')||'<p class="small muted">No new tasks are ready in the current band. Continue a prerequisite, revisit your mistakes, or browse the library.</p>'}</div><div class="card pad"><h2>How difficulty changes</h2><p>Codeforces starts around 800. AtCoder starts with its lowest estimated band.</p><p class="small muted">Each task contributes evidence once. Four independent solves within 45 minutes out of five distinct tasks near your current level raise the band by 100. Three stuck results in that group lower it by 100, down to the starting floor. Unrated tasks do not change a numeric band.</p><p class="small muted">LeetCode begins with Easy tasks. Ten distinct independent Easy solves unlock Medium recommendations; thirty independent Medium solves unlock Hard. These are local practice rules, not official ratings.</p><a class="btn" href="#practice">Browse every indexed task</a></div></div>`+
    `<div class="month-grid">${[
      ['Month 1','Language fluency and reliable basics','Read input, trace loops, use arrays and maps, test tiny cases.',settings().primaryLanguage==='python'?['hello','input','loops','lists','functions','counting']:settings().primaryLanguage==='c'?['c-start','c-io','c-control','c-arrays']:['cpp-start','cpp-io','cpp-control','cpp-sequences','cpp-stl-fast-io']],
      ['Month 2','Recognize common patterns','Sorting, binary search, prefix sums, two pointers, windows, stacks and greedy proofs.',['sorting','binary','prefix','twopointers','window','stack','greedy']],
      ['Month 3','Connect states and structures','BFS/DFS, trees, heaps and dynamic programming; explain why each transition is valid.',['bfs','dfs','heap','dp','tree-dp']],
      ['Month 4','Mix, time, and repair','Timed sets, delayed re-solves and targeted advanced study from the errors you actually make.',['contest','knapsack','dsu','prefix-function']]
    ].map(([name,title,description,ids],i)=>`<article class="card pad"><span class="eyebrow muted">${name} · ${C.addMonths(s.start,i)}–${C.addMonths(s.start,i+1)}</span><h2>${title}</h2><p class="small muted">${description}</p><div class="month-links">${phaseLinks(ids.filter(id=>L(id)||nativeLessons.some(l=>l.id===id)))}</div></article>`).join('')}</div><p class="small muted">These phases guide topic order. Your next lesson follows prerequisites and your next problems follow evidence; a date never grants a skill automatically.</p>`;
  }
  function planSettings(){const s=settings();modal(modalHead('Your four-month plan')+`<form onsubmit="ForgeStudy.savePlan(event)"><div class="field"><label for="plan-start">Start date</label><input id="plan-start" name="start" type="date" required value="${s.start}"></div><div class="field"><label for="plan-language">Primary practice language</label><select id="plan-language" name="language">${[['python','Python'],['c','C'],['cpp','C++']].map(([v,t])=>`<option value="${v}" ${s.primaryLanguage===v?'selected':''}>${t}</option>`).join('')}</select></div><div class="field"><label for="plan-scope">LeetCode completion goal</label><select id="plan-scope" name="scope"><option value="all" ${s.scope==='all'?'selected':''}>All indexed problems, including SQL and JavaScript</option><option value="algorithms" ${s.scope==='algorithms'?'selected':''}>Algorithm problems only</option></select></div><div class="field"><label for="plan-estimate">Initial estimate: minutes per problem</label><input id="plan-estimate" name="estimate" type="number" min="5" max="180" value="${s.minutesPerProblem}" required></div><label class="inline-check"><input name="premium" type="checkbox" ${s.premium?'checked':''}> Include Premium-marked tasks in my daily recommendations</label><p class="small muted">The end date will be four calendar months after the start. Daily available time comes from your existing Settings and check-in.</p><button class="btn primary">Save plan</button></form>`);}
  function savePlan(event){event.preventDefault();const f=new FormData(event.target),s={...settings(),start:String(f.get('start')),primaryLanguage:String(f.get('language')),scope:String(f.get('scope')),minutesPerProblem:Number(f.get('estimate')),premium:f.get('premium')!==null};if(!C.validDate(s.start)){toast('Choose a valid start date.');return;}s.end=C.addMonths(s.start,4);try{C.validate(s);}catch(e){toast(e.message);return;}state.study=s;save();closeModal();go('roadmap');}
  settingsView=function(){return previous.settingsView()+`<section class="card pad lesson-sources"><h2>Four-month learning campaign</h2><p class="muted">${settings().start} → ${settings().end} · Primary language: ${settings().primaryLanguage.toUpperCase()}</p><button class="btn primary" onclick="ForgeStudy.planSettings()">Edit four-month plan</button></section>`;};
  resourcesView=function(){return pageHead('YOUR REFERENCE SHELF','The right source for each idea.','Every lesson has a specific reading selection. Open the lesson to use its prefilled Python Tutor visualization.')+`<div class="card pad"><h2>Visualize and practice here</h2><div class="reference-list"><a class="quick-link" href="#practice">LeetCode, Codeforces and AtCoder problem library ${icon('arrow',13)}</a><a class="quick-link" href="#curriculum">Four-month curriculum and K&R C reading track</a><a class="quick-link" href="#roadmap">Four-month adaptive plan ${icon('arrow',13)}</a><button class="quick-link textbtn" onclick="ForgeStudy.visualizeLesson('hello')">Python Tutor inside Forge ${icon('play',13)}</button></div></div><div class="reference-directory">${[['Python',LESSONS],['C',nativeLessons.filter(l=>l.language==='c')],['C++ and algorithms',nativeLessons.filter(l=>l.language==='cpp')]].map(([name,lessons])=>`<section class="card pad"><h2>${name}</h2>${lessons.map(l=>`<div class="reference-directory-row"><a href="#${name==='Python'?'learn':'native'}/${l.id}"><b>${esc(l.title)}</b></a>${(refs[l.id]||[]).map(r=>`<span class="small">${link(r.url,r.title)}</span>`).join('')}</div>`).join('')}</section>`).join('')}</div><p class="small muted">${link('https://github.com/axsimarosmelos/forge/blob/main/content/catalog/NOTICE.md','Catalog, video and editorial credits')}</p>`;};
  updateChrome=function(){previous.updateChrome();const s=settings(),duration=C.days(s.start,s.end),day=Math.max(1,Math.min(duration,C.days(s.start,today())+1));$('#side-day').textContent=String(day).padStart(2,'0')+' / '+duration;const route=location.hash.slice(1).split('/')[0];if(['practice','problem'].includes(route))$('#crumb').textContent='Problem library';if(route==='roadmap')$('#crumb').textContent='Four-month plan';};
  render=function(){const route=(location.hash.slice(1)||'today').split('/');
    if(['practice','problem','roadmap','prep'].includes(route[0])){updateChrome();$('#app').innerHTML=(route[0]==='practice'?libraryView():route[0]==='problem'?problemView(route[1]):route[0]==='roadmap'?planView():`<div class="language-tabs"><a class="btn" href="#roadmap">Four-month learning plan</a><a class="btn primary" href="#prep">Competition preparation</a></div>`+previous.roadmapView())+footer();document.title='Forge · '+(route[0]==='problem'?problem(route[1])?.title||'Problem':route[0]==='roadmap'?'Four-month plan':'Problem library');if(route[0]==='practice')renderCatalogRows();if(route[0]==='problem'){paintProblemEditor(route[1]);if(openedEditorial.has(route[1]))loadMath();}}
    else{previous.render();if(route[0]==='native'&&nativeLessons.some(l=>l.id===route[1])){const node=document.createElement('div');node.innerHTML=referencePanel(route[1]);$('#app').prepend(node);}if(route[0]==='lab'){const panel=document.createElement('div');panel.className='banner';panel.innerHTML='<button class="textbtn" onclick="ForgeStudy.visualizeLab()">Visualize this code with Python Tutor</button> · Step through memory inside Forge.';$('#app').prepend(panel);}if(route[0]==='today'){const banner=document.createElement('div');banner.className='card pad campaign-banner';banner.innerHTML=`<div><span class="eyebrow muted">YOUR FOUR-MONTH CAMPAIGN</span><h2>Learn. Attempt. Recall. Adjust.</h2><p class="small muted">${settings().start} → ${settings().end} · LeetCode, Codeforces and AtCoder in your problem library.</p></div><div class="flex wrap"><a class="btn primary" href="#roadmap">Today’s adaptive plan →</a><a class="btn" href="#practice">Open problem library</a></div>`;$('#app').prepend(banner);}}
  };
  document.addEventListener('keydown',event=>{if(event.key==='Tab'&&event.target.id==='problem-code'){event.preventDefault();const input=event.target,a=input.selectionStart,b=input.selectionEnd;input.value=input.value.slice(0,a)+'    '+input.value.slice(b);input.selectionStart=input.selectionEnd=a+4;updateWorkspace(location.hash.split('/')[1],'code',input.value);}});
  window.ForgeStudy={workspace,nativeLessons,displayTutor,isRunning:()=>!!runContext,markHelp,referencePanel,visualizeLesson,visualizeLab:labVisualization,visualizeProblem:id=>ForgeLearning.visualize(id),setFilter,search:value=>{filters.query=value;filters.page=0;clearTimeout(searchTimer);searchTimer=setTimeout(renderCatalogRows,150);},page:delta=>{filters.page=Math.max(0,filters.page+delta);renderCatalogRows();window.scrollTo(0,0);},reload:()=>{C.platforms.forEach(p=>loadCatalog(p,true));},retry:p=>loadCatalog(p,true),update:updateWorkspace,syncScroll:syncProblemScroll,language:(id,language)=>{if(!ForgeLearningCore.language(language))return;if(runContext?.id===id)stopRun();const w=workspace(id);w.language=language;if(!Object.hasOwn(w.drafts,language))w.drafts[language]=language==='javascript'?'console.log(19);\n':'';dirtyWorkspace(id);save();render();},showVideo,saveVideo,reveal,loadTemplate,addRecall,saveRecall,log,run:runProblem,stop:()=>{stopRun();window.ForgeLearning?.stop();},planSettings,savePlan,download:id=>{const w=workspace(id);download(id+'.'+(w.language==='python'?'py':w.language==='c'?'c':w.language==='cpp'?'cpp':w.language==='javascript'?'js':'txt'),w.drafts[w.language],'text/plain');},
    // Exposed read-only/pure helpers support transparent diagnostics and regression tests.
    acceptCatalog:accept,allProblems,mergedAttempts,dailyTasks,proseHTML,editorialHTML,loadAll};
  render();if(typeof fetch==='function'&&location.protocol!=='file:')void loadAll();
})();
