const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
vm.runInThisContext(fs.readFileSync(path.join(__dirname,'../frontend/catalog-core.js'),'utf8'));
const C=ForgeCatalogCore;
assert.equal(C.addMonths('2026-10-31',4),'2027-02-28');
assert.equal(C.addMonths('2023-10-31',4),'2024-02-29');
assert.equal(C.addMonths('2026-09-15',4),'2027-01-15');
assert.equal(C.validDate('2026-02-30'),false);
assert.equal(C.days('2026-09-15','2027-01-15'),122);
const defaults=C.defaults('2026-09-15');C.validate(defaults);
const task=(n,platform='LeetCode',extra={})=>({id:platform==='LeetCode'?'lc-'+n:platform==='Codeforces'?'cf-'+n+'-A':'at-abc'+n+'_a',number:n,platform,title:'Task '+n,url:platform==='LeetCode'?'https://leetcode.com/problems/example/':platform==='Codeforces'?'https://codeforces.com/problemset/problem/'+n+'/A':'https://atcoder.jp/contests/abc/tasks/abc_a',difficulty:'Easy',rating:platform==='LeetCode'?null:platform==='Codeforces'?800:0,tags:[],premium:false,kind:'algorithm',...extra});
const attempt=(n,platform='Codeforces',extra={})=>({pid:task(n,platform).id,platform,outcome:'independent',minutes:20,note:'Derived independently',at:n*1000,difficulty:platform==='LeetCode'?'Easy':'800',rating:platform==='LeetCode'?null:800,...extra});
const wins=Array.from({length:5},(_,i)=>attempt(i+1));
assert.equal(C.level(wins,'Codeforces').rating,900);
assert.equal(C.level(Array.from({length:20},(_,i)=>attempt(1,'Codeforces',{at:i})),'Codeforces').rating,800,'repeated task cannot farm a higher band');
assert.equal(C.level(wins.map(a=>({...a,rating:null})),'Codeforces').rating,800,'unrated task is not numeric evidence');
assert.equal(C.level(wins.map(a=>({...a,minutes:80})),'Codeforces').rating,800,'slow independent attempts do not advance the timed band');
const losses=Array.from({length:5},(_,i)=>attempt(i+6,'Codeforces',{rating:900,outcome:'stuck'}));
assert.equal(C.level([...wins,...losses],'Codeforces').rating,800);
assert.equal(C.level(losses,'Codeforces').rating,800,'difficulty floor respected');
assert.equal(C.level(Array.from({length:5},(_,i)=>attempt(i+1,'AtCoder',{rating:0})),'AtCoder').rating,100);
const easy=Array.from({length:10},(_,i)=>attempt(i+1,'LeetCode'));
assert.equal(C.leetcodeLevel(easy),2);
assert.equal(C.leetcodeLevel(Array(10).fill(easy[0])),1);
assert.equal(C.leetcodeLevel([...easy,...Array.from({length:30},(_,i)=>attempt(i+100,'LeetCode',{difficulty:'Medium'}))]),3);
const tasks=[task(1),task(2),task(3,'LeetCode',{kind:'sql',premium:true})];
let pace=C.pace(defaults,tasks,[easy[0],easy[0]],'2026-09-15',180);
assert.equal(pace.done,1);assert.equal(pace.total,3);assert.equal(pace.left,122);assert.equal(pace.capacity,5);assert.equal(pace.otherLanguages,1);assert.equal(pace.premium,1);
assert.equal(C.pace({...defaults,scope:'algorithms'},tasks,[],'2026-09-15',180).total,2);
assert.equal(C.pace(defaults,tasks,[],'2027-01-16',180).required,null);
assert.equal(C.pace(defaults,tasks,tasks.map(p=>attempt(p.number,'LeetCode')),'2027-01-16',180).required,0);
const pool=[task(1),task(2,'LeetCode',{difficulty:'Hard'}),task(3,'LeetCode',{premium:true}),task(4,'LeetCode',{kind:'sql'}),task(5,'Codeforces'),task(6,'Codeforces',{rating:1800}),task(7,'Codeforces',{rating:null})];
const options={now:100000000,premium:false,ready:()=>true};
assert.deepEqual(C.recommendations(pool,[],options).map(x=>x.problem.id).sort(),['cf-5-A','lc-1']);
assert.equal(C.recommendations(pool,[],{...options,ready:()=>false}).length,0);
assert.equal(C.recommendations(pool,[attempt(1,'LeetCode',{outcome:'hinted',at:options.now-100})],options).some(x=>x.problem.id==='lc-1'),false,'guided tasks get a delay');
assert.equal(C.recommendations(pool,[easy[0]],options).some(x=>x.problem.id==='lc-1'),false,'solved tasks are excluded');
const valid={platform:'LeetCode',fetchedAt:'2026-09-15',problems:[task(1)]};C.catalog(valid);
for(const extra of [{url:'javascript:alert(1)'},{url:'https://leetcode.com.evil.test/'},{video:{id:'bad" onload="x'}},{editorialBatch:'../../x'},{kind:'unexpected'}])assert.throws(()=>C.catalog({...valid,problems:[task(1,'LeetCode',extra)]}));
assert.throws(()=>C.catalog({...valid,problems:[task(1),task(1)]}));
assert.throws(()=>C.validate({...defaults,attempts:[{...easy[0],outcome:'accepted'}]}));
assert.throws(()=>C.validate({...defaults,workspaces:{'__malformed__':{}}}));
assert.equal(C.videoID('https://youtu.be/KLlXCFG5TnA'),'KLlXCFG5TnA');
assert.equal(C.videoID('https://youtube.com.evil.test/watch?v=KLlXCFG5TnA'),'');
assert.equal(C.videoID('javascript:alert(1)'),'');
const tutor=new URL(C.tutorURL('print("a#b&c")','python','4\n9\n',true)),params=new URLSearchParams(tutor.hash.slice(1));
assert.equal(tutor.hostname,'pythontutor.com');assert.equal(params.get('code'),'print("a#b&c")');assert.equal(params.get('py'),'3');assert.deepEqual(JSON.parse(params.get('rawInputLstJSON')),['4','9']);
console.log('PASS: calendar-month dates, completion pace, distinct evidence, difficulty adaptation, delayed repairs, readiness, metadata validation and visualizer encoding.');
