from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
modules=[]
def module(id,title,language,description):
 m=dict(id=id,title=title,language=language,description=description,lessons=[]); modules.append(m); return m
c=module('c-foundations','C foundations for contests','c','Learn explicit types, input, arrays, addresses, and memory. C is an optional track; it is not a prerequisite for C++.')
cpp=module('cpp-foundations','C++ foundations for contests','cpp','Start with C++17 before learning the STL. Pick one primary contest language while building fluency.')
def foundation(m,id,title,prereqs,body,code,stdin,output,checks,cards):
 m['lessons'].append(dict(id=id,title=title,language=m['language'],level='foundation',content_status='complete',prerequisites=prereqs,estimated_minutes=35,objectives=[body[0].split('. ')[0]+'.'],body=body,code=code,stdin=stdin,expected_output=output,checks=[dict(q=q,answers=a,why=w) for q,a,w in checks],recall_cards=[dict(q=q,a=a) for q,a in cards],source_urls=['https://gcc.gnu.org/onlinedocs/'],practice={'type':'trace-and-modify','instruction':'Predict the output, run the example, change one input or value, and explain the change.'},mastery_gate={'quiz_correct':len(checks),'independent_application_required':True}))
foundation(c,'c-start','A C program, from zero',[],[
'A C program is source text that a compiler translates into an executable program. Compilation checks language rules; executing the resulting program performs its instructions. A successful compilation does not prove your algorithm is correct.',
'#include <stdio.h> makes standard input/output declarations available. int main(void) is the entry point. Braces group statements, and a semicolon ends most statements. printf writes output; \\n inside a string means a newline.',
'A declaration such as int score = 10 creates an integer variable and initializes it. score = score + 7 computes the right side using the old value, then stores the result. C names are case-sensitive. Read from initialized variables only.',
'Use +, -, *, /, and % for arithmetic. Integer division truncates toward zero, so 7 / 2 is 3. Unlike Python’s unbounded integers, C integers have finite ranges. Signed overflow is undefined behavior: choose types and bounds deliberately.'],
'#include <stdio.h>\nint main(void) {\n    int score = 10;\n    score = score + 7;\n    printf("%d\\n", score);\n    return 0;\n}', '', '17\n',
[('What value is printed?',['17'],'10 + 7 is assigned back to score.'),('What is integer 7 / 2 in C?',['3'],'Integer division truncates toward zero.')],
[('What happens before a C program runs?','Its source is compiled into an executable.'),('Why is signed integer overflow dangerous in C?','It is undefined behavior, not guaranteed wraparound.')])
foundation(c,'c-io','Read and print exact values',['c-start'],[
'Formatted input in C connects a format string to addresses where values will be stored. scanf("%d", &n) reads an int into n. The & operator supplies its address. Missing it for a scalar is a serious bug.',
'Use %d with int and %lld with long long. The declared type and format must agree. scanf returns the number of successful conversions; check it before using the variables. Whitespace between numeric input values can be spaces or newlines.',
'printf uses the same integer format names to display values, but receives the values, not their addresses. Print exactly what the judge requests. Extra prompts and debug messages make otherwise correct output wrong.',
'For input-heavy contests, buffered scanf/printf are a reasonable starting point. A custom parser is a later optimization, after correctness and profiling. In C, line-based text input can use fgets with a buffer size; never use removed, unsafe gets.'],
'#include <stdio.h>\nint main(void) {\n    long long a, b;\n    if (scanf("%lld %lld", &a, &b) != 2) return 0;\n    printf("%lld\\n", a + b);\n    return 0;\n}', '7 12\n','19\n',
[('How many successful conversions should reading two integers return?',['2'],'Each parsed integer counts as one conversion.'),('For an int n, does scanf need n or &n?',['&n'],'scanf needs the address where it will store the value.')],
[('Which format matches long long?','%lld'),('Why check scanf’s return value?','To avoid using variables when expected input was not successfully read.')])
foundation(c,'c-control','Decisions and loops in C',['c-io'],[
'Comparisons such as n >= 0 produce a truth value. if executes its block for a nonzero condition; else handles the remaining case. Equality uses ==, while = assigns. Use braces even when a block has one statement.',
'Combine conditions with && for and, || for or, and ! for not. The expression n % 2 == 0 tests evenness. && and || short-circuit, so the second condition runs only if it is needed.',
'for (int i = 0; i < n; ++i) initializes i once, checks the condition before each iteration, and increments after the body. A while loop repeats while its condition holds. Make sure the state progresses toward stopping.',
'Initialize an accumulator before the loop that uses it. Reset it between independent test cases. Trace the smallest allowed case and exact thresholds; off-by-one errors do not disappear when you change programming languages.'],
'#include <stdio.h>\nint main(void) {\n    int count = 0;\n    for (int i = 1; i <= 10; ++i) {\n        if (i % 2 == 0) ++count;\n    }\n    printf("%d\\n", count);\n    return 0;\n}', '', '5\n',
[('How many even numbers from 1 through 10 are counted?',['5'],'They are 2, 4, 6, 8, 10.'),('Which compares equality: = or ==?',['=='],'A single equals sign is assignment.')],
[('How is logical and written in C?','&&'),('Where do you initialize an accumulator?','Before its accumulating loop, and separately for each independent case.')])
foundation(c,'c-arrays','Arrays and null-terminated strings',['c-control'],[
'An array stores a fixed number of same-type elements contiguously. int a[3] = {4, 8, 2} has valid indices 0, 1, 2. C does not automatically check an array index. Reading or writing outside the array is undefined behavior.',
'The expression sizeof(a) / sizeof(a[0]) can count elements when a is an actual array in the current scope. It does not recover the length from a pointer or from an array parameter inside a function. Pass lengths explicitly.',
'A C string is a character sequence ending in a zero byte, written \\0. A buffer must include space for that terminator. char word[8] can hold at most seven ordinary characters plus the terminator. Use scanf("%7s", word) for one whitespace-delimited word in that buffer.',
'For text that may contain spaces, use fgets(buffer, sizeof buffer, stdin), and account for the newline it may retain. Arrays are not assignable as whole values in C. Use loops or appropriate library operations to copy their elements.'],
'#include <stdio.h>\nint main(void) {\n    int a[3] = {4, 8, 2};\n    int sum = 0;\n    for (int i = 0; i < 3; ++i) sum += a[i];\n    printf("%d\\n", sum);\n    return 0;\n}', '', '14\n',
[('What is the last valid index in an array of length 3?',['2'],'Indices start at zero.'),('How many ordinary characters fit in char word[8] as a terminated string?',['7'],'One byte is reserved for the null terminator.')],
[('Does C automatically check array bounds?','No. You must keep indices within the allocated range.'),('What marks the end of a C string?','A zero byte, written \\0.')])
foundation(c,'c-pointers','Functions, addresses, and pointers',['c-arrays'],[
'A function packages instructions behind a name, parameters, and a return type. Parameters are passed by value in C: changing an ordinary parameter does not change the caller’s variable.',
'A pointer stores an address. In int *p = &x, &x is x’s address and *p accesses the int at that address. Only dereference a pointer that points to a live, suitable object. A null or dangling pointer is not usable storage.',
'Pass a pointer when a function must modify the caller’s object. Arrays passed to functions are represented through pointers; the function needs a separate length argument. const int *a promises not to modify elements through that pointer.',
'A local automatic variable stops existing when its block ends. Returning its address creates a dangling pointer. Prefer returning a value, modifying caller-owned storage, or using explicitly managed allocation with a clear owner.'],
'#include <stdio.h>\nvoid add_one(int *p) {\n    ++(*p);\n}\nint main(void) {\n    int x = 4;\n    add_one(&x);\n    printf("%d\\n", x);\n    return 0;\n}', '', '5\n',
[('What is x after add_one(&x) when x starts at 4?',['5'],'The function changes the object at x’s address.'),('Does *p mean address-of or dereference?',['dereference'],'It accesses the pointed-to object.')],
[('How do you obtain x’s address?','&x'),('Why must you not return the address of an automatic local variable?','Its lifetime ends when the function exits, leaving a dangling pointer.')])
foundation(c,'c-memory','Allocate, bound, and release memory',['c-pointers'],[
'When an array length is only known at runtime, dynamically allocated storage can hold its elements. malloc returns a pointer or NULL if allocation fails. Include stdlib.h, check for failure, and release the allocation exactly once with free.',
'Compute allocation sizes without overflow. Check n <= SIZE_MAX / sizeof *a before requesting n * sizeof *a bytes. Validate signed inputs before converting them to size_t, which is unsigned.',
'free ends the allocation’s lifetime. Do not read or write through the old pointer afterward, and do not free it again. A pointer assignment copies an address, not the allocation. Decide which part of your program owns the storage.',
'For debugging your own code locally, compiler warnings and address/undefined-behavior sanitizers can expose mistakes. They are debugging tools, not an untrusted-code sandbox. For C++ contests, vector usually makes ownership simpler than manual malloc/free.'],
'#include <stdio.h>\n#include <stdlib.h>\n#include <stdint.h>\nint main(void) {\n    size_t n = 3;\n    if (n > SIZE_MAX / sizeof(int)) return 1;\n    int *a = malloc(n * sizeof *a);\n    if (a == NULL) return 1;\n    for (size_t i = 0; i < n; ++i) a[i] = (int)i + 1;\n    printf("%d\\n", a[2]);\n    free(a);\n    return 0;\n}', '', '3\n',
[('Which function releases malloc-allocated storage?',['free','free()'],'Each successful allocation needs a clear owner that releases it once.'),('Is it valid to read an allocation after free? Answer yes or no.',['no'],'The allocated object’s lifetime has ended.')],
[('What must you check before allocating n elements?','That the byte-count multiplication cannot overflow and that allocation succeeds.'),('What does copying a pointer copy?','The address, not the pointed-to allocation.')])
foundation(cpp,'cpp-start','Your first C++17 program',[],[
'C++ source is compiled before execution. A compiler translates valid source into a program; it cannot prove that the program solves your problem. Compile errors, runtime errors, and wrong answers are different kinds of feedback.',
'#include <iostream> declares stream input and output. int main() is the entry point. Braces group statements and semicolons end most statements. std::cout writes values with <<. The character literal \'\\n\' writes a newline.',
'Declare a variable with a type: int score = 10. Assignment stores a value; == compares two values. long long is useful for larger sums, but it is still bounded. Signed overflow is undefined behavior.',
'Use explicit initialization. The compiler will not safely invent a value for an uninitialized local integer. Predict the result of each line, then compile and run a small complete program.'],
'#include <iostream>\nint main() {\n    int score = 10;\n    score += 7;\n    std::cout << score << \'\\n\';\n}', '', '17\n',
[('What value is printed?',['17'],'The variable increases from 10 to 17.'),('Does compilation alone prove that your algorithm is correct? Answer yes or no.',['no'],'It checks language rules, not whether you solved the task.')],
[('What is main?','The program’s entry point.'),('How do you write a newline without explicitly flushing cout?',"std::cout << '\\n';")])
foundation(cpp,'cpp-io','C++ input and output',['cpp-start'],[
'std::cin >> a >> b reads two whitespace-separated values into existing variables. The operator selects conversions from their declared types. Test the stream result before using values when input might be missing.',
'For ordinary batch contests, call std::ios::sync_with_stdio(false) and std::cin.tie(nullptr) before I/O. These disable C/C++ stream synchronization and remove cin’s automatic tie to cout. Avoid mixing scanf/printf with unsynchronized cin/cout.',
'Use \'\\n\' for ordinary newlines. std::endl also flushes the output buffer. Interactive problems need explicit flushing before you wait for the judge; optimization must not break the protocol.',
'Use std::getline for a whole text line. Numeric extraction can leave a newline waiting, so reason about that transition. Do not print prompts or assume an initial test-case count unless the statement specifies one.'],
'#include <iostream>\nint main() {\n    std::ios::sync_with_stdio(false);\n    std::cin.tie(nullptr);\n    long long a, b;\n    if (!(std::cin >> a >> b)) return 0;\n    std::cout << a + b << \'\\n\';\n}', '7 12\n','19\n',
[('What extra action does std::endl perform after a newline?',['flush','flushes','flushing'],'It flushes the output stream.'),('For input 7 12, what sum is printed?',['19'],'Both extracted integers are added.')],
[('What does cin.tie(nullptr) remove?','The tied output stream that would otherwise be flushed before input operations.'),('When must you explicitly flush output?','When an interactive protocol needs to receive your query before replying.')])
foundation(cpp,'cpp-control','Conditions and loops',['cpp-io'],[
'Use if, else if, and else to select a block. Comparisons use ==, !=, <, <=, >, >=. Combine conditions with &&, ||, and !. A nonzero scalar condition is treated as true.',
'A for loop has initialization, condition, and update sections. for (int i = 0; i < n; ++i) visits zero through n - 1. The check happens before the body, so n = 0 gives no iterations.',
'A while loop repeats while its condition holds. Make progress toward stopping. break exits the nearest loop; continue skips to its next iteration. Braces make the boundaries of blocks explicit.',
'Counters and sums must be initialized before accumulating. Reset them for each independent test case. Test a condition exactly at its threshold as well as on each side.'],
'#include <iostream>\nint main() {\n    int sum = 0;\n    for (int i = 1; i <= 4; ++i) sum += i;\n    std::cout << sum << \'\\n\';\n}', '', '10\n',
[('What is the sum from 1 through 4?',['10'],'1 + 2 + 3 + 4 is 10.'),('How many iterations does for (int i=0; i<3; ++i) perform?',['3'],'It visits 0, 1, and 2.')],
[('What is the distinction between i < n and i <= n in a zero-based loop?','The latter includes n and may access beyond an n-element sequence.'),('What keeps a while loop from running forever?','A state change that eventually makes its condition false.')])
foundation(cpp,'cpp-functions','Functions, references, and const',['cpp-control'],[
'Functions name a computation. int add(int a, int b) receives copies of two integers and returns an integer. return sends a value to the caller; printing merely displays output.',
'A reference parameter such as int& x refers to the caller’s object. Updating x changes that object. Pass a large read-only structure as const T& to avoid copying while preventing modification through that reference.',
'const communicates a restriction on modification. auto asks the compiler to deduce a type from an initializer; it does not mean that the variable can dynamically change type like a Python name.',
'An object’s lifetime matters. Do not return a reference or pointer to an automatic local variable. Avoid unnecessary copies in a loop, but also avoid retaining references that a later container operation may invalidate.'],
'#include <iostream>\nvoid add_one(int& x) { ++x; }\nint main() {\n    int x = 4;\n    add_one(x);\n    std::cout << x << \'\\n\';\n}', '', '5\n',
[('What does x become in this program?',['5'],'The reference parameter modifies the caller’s x.'),('For a large read-only object, prefer a copy or const reference?',['const reference','const t&','const&'],'A const reference avoids the copy and prevents modification through it.')],
[('How is int x different from int& x as a parameter?','The first is a copy; the second refers to the caller’s object.'),('What does auto do?','It deduces a fixed compile-time type from the initializer.')])
foundation(cpp,'cpp-sequences','Vectors and strings',['cpp-functions'],[
'std::vector<T> is a resizable contiguous sequence. std::vector<int> a{4, 8, 2} has three elements. Indices start at zero; a.size() gives the number of elements. Indexing with [] does not automatically check bounds.',
'push_back appends. A range-for loop visits elements: for (int x : a) copies each int; for (auto& x : a) allows modifications. reserve increases capacity without creating elements, while resize changes the number of elements.',
'std::string manages a sequence of characters. Use .size(), indexing, concatenation, and standard algorithms rather than manually reserving a null terminator as with a raw C character buffer. cin >> word reads a whitespace-delimited word; getline reads a line.',
'A vector append may reallocate its storage and invalidate references and iterators. Do not keep an iterator across an operation that might invalidate it. For nested vectors, each inner vector has its own size and allocation.'],
'#include <iostream>\n#include <vector>\nint main() {\n    std::vector<int> a{4, 8, 2};\n    a.push_back(5);\n    long long sum = 0;\n    for (int x : a) sum += x;\n    std::cout << sum << \'\\n\';\n}', '', '19\n',
[('What is the sum after appending 5?',['19'],'4 + 8 + 2 + 5 is 19.'),('Does reserve(10) create ten elements? Answer yes or no.',['no'],'It changes capacity, not size.')],
[('What is the difference between reserve and resize?','reserve provides capacity; resize changes the actual number of elements.'),('Why can push_back invalidate a reference?','It may move the vector’s elements into a newly allocated buffer.')])
foundation(cpp,'cpp-costs','Types, cost, and contest constraints',['cpp-sequences'],[
'Big-O describes how work grows with input size. One complete scan is O(n); all ordered pairs usually require O(n²). Two consecutive scans still take O(n), whereas two full nested scans take O(n²).',
'A problem with n = 200,000 usually rules out a straightforward quadratic scan under normal contest limits. Faster syntax cannot fix an unsuitable growth rate. Estimate both the number of operations and extra memory.',
'Widen arithmetic before it overflows: 1LL * a * b evaluates the product in long long when a and b are ints. long long answer = a * b can overflow in the int expression before assignment. All intermediate values still need to fit.',
'Prefer using aliases and constexpr constants to broad macros. #define int long long rewrites tokens throughout your program and hides types. A macro can evaluate an argument multiple times. A function has clearer type and evaluation rules.'],
'#include <iostream>\nusing i64 = long long;\nint main() {\n    int a = 100000, b = 100000;\n    i64 product = 1LL * a * b;\n    std::cout << product << \'\\n\';\n}', '', '10000000000\n',
[('What is the product of 100000 and 100000?',['10000000000'],'It exceeds a typical signed 32-bit int range.'),('Two full nested n-element loops have O(n) or O(n^2) growth?',['o(n^2)','n^2','o(n²)'],'Each of n outer visits has n inner visits.')],
[('Why does assigning a*b to long long not always prevent overflow?','a*b can be computed in int before the result is assigned.'),('What is preferable to #define int long long?','An explicit long long declaration or a using alias such as using i64 = long long.')])
stl=module('cpp-stl','C++ STL & Fast I/O','cpp','The first full deep-dive module: container selection, efficient I/O, sorting contracts, binary search, and an original practice problem.')
md=(ROOT/'content/cpp-stl-fast-io.md').read_text()
stl['lessons'].append(dict(id='cpp-stl-fast-io',title='C++ STL for Competitive Programming & Fast I/O',language='cpp',level='core',content_status='complete',prerequisites=['cpp-costs'],estimated_minutes=120,objectives=['Choose a container by required operations and complexity.','Use batch and interactive I/O correctly.','Explain iterator validity and lower/upper-bound contracts.','Solve static threshold queries without discarding duplicates.'],markdown_path='content/cpp-stl-fast-io.md',template_paths=['templates/cpp17-starter.cpp','templates/stl-workbench.cpp','templates/scoreboard-thresholds.cpp'],code=(ROOT/'templates/scoreboard-thresholds.cpp').read_text(),stdin='5 4\n10 20 20 40 50\n20\n21\n51\n0\n',expected_output='4 20\n2 40\n0 -1\n5 10\n',checks=[dict(q='First value at least x: lower_bound or upper_bound?',answers=['lower_bound'],why='lower_bound includes equality; upper_bound excludes it.'),dict(q='Does map[key] insert a missing key? Answer yes or no.',answers=['yes'],why='operator[] inserts a value-initialized mapped value when absent.')],recall_cards=[dict(q=q,a=a) for q,a in [('When is std::endl necessary instead of a plain newline?','Use an explicit flush when an interactive judge must receive your query before replying.'),('What must you check before dereferencing lower_bound’s result?','That the result is not end().'),('What happens to a vector’s size after reserve?','It stays the same; only capacity may increase.'),('Why is <= not a valid sorting comparator?','It is not strict: an element can compare before itself.'),('What type does accumulate(..., 0LL) use?','A long long accumulator.'),('What guarantees differ between map and unordered_map?','map maintains order with logarithmic operations; unordered_map has average constant-time lookup and linear worst cases.')]],practice={'id':'scoreboard-thresholds','type':'original','title':'Scoreboard Thresholds','statement_markdown_path':'content/cpp-stl-fast-io.md','solution_path':'templates/scoreboard-thresholds.cpp','independent_reconstruction_required':True},mastery_gate={'quiz_correct':2,'independent_application_required':True},source_urls=['https://eel.is/c++draft/ios.members.static','https://eel.is/c++draft/alg.binary.search','https://cp-algorithms.com/']))
# Each advanced entry is a complete machine-readable lesson plan, not falsely labeled as a written article.
def advanced(m,id,title,pre,summary,time,space,pitfall,exercise,path,level='advanced'):
 m['lessons'].append(dict(id=id,title=title,language='cpp',level=level,content_status='blueprint',prerequisites=pre.split(),estimated_minutes=90 if level=='core' else 150,objectives=[summary,'Derive the invariant or recurrence, justify correctness, and account for time and memory.','Implement from a blank file and compare with a small-input reference.'],study_outline=[{'step':'Model','task':summary},{'step':'Derive','task':'Work through a small example and state exactly what each stored value means.'},{'step':'Prove','task':'Identify the maintained invariant or induction hypothesis; justify each update.'},{'step':'Implement','task':'Write C++17 with explicit bounds, types, and ownership. Avoid relying on an unexplained template.'},{'step':'Stress-test','task':exercise},{'step':'Transfer','task':'Change one assumption and explain whether the same method still applies.'}],complexity={'time':time,'extra_space':space,'model':'State parameters explicitly; bounds assume ordinary word-sized arithmetic unless noted.'},common_pitfalls=[pitfall,'Confusing successful compilation or a memorized template with a correctness argument.'],practice={'type':'implementation-and-oracle','task':exercise,'steps':['Solve a tiny instance by hand.','Implement a straightforward oracle for small inputs.','Compare the optimized result against the oracle on random and boundary cases.','Return after a delay and reconstruct the invariant.']},mastery_gate={'explain_invariant':True,'independent_implementation':True,'randomized_cross_check':True,'unseen_transfer_problem':True},recall_cards=[dict(q=f'What is the central idea behind {title}?',a=summary),dict(q=f'What assumption or boundary can break {title}?',a=pitfall)],source_urls=['https://cp-algorithms.com/'+path]))
a=module('algebra','Algebra & number theory','cpp','Arithmetic structure, primes, modular methods, and combinatorial computation.')
rows=[
('gcd','Euclid, extended GCD, and linear Diophantine equations','cpp-stl-fast-io','Use remainders to preserve the gcd; track Bézout coefficients to solve ax + by = c.','O(log min(a,b)) word operations','O(1) iterative state','A solution exists only if gcd(a,b) divides c; normalize signs and handle zero inputs.','Compare gcd and Bézout identities across small signed pairs.','algebra/extended-euclid-algorithm.html'),
('binary-power','Binary exponentiation','cpp-stl-fast-io','Represent the exponent in binary and square the base while maintaining the accumulated power.','O(log e) multiplications','O(1)','Multiplication can overflow before reduction; exponent zero needs the identity element.','Compare with repeated multiplication for small exponents, including zero.','algebra/binary-exp.html'),
('sieve','Prime sieves and smallest prime factors','cpp-stl-fast-io','Mark composites from each prime’s square and optionally store the smallest prime factor.','O(n log log n) for Eratosthenes','O(n)','Starting at p*p can overflow an int before checking the bound.','Compare prime flags and factorizations with trial division up to 10000.','algebra/sieve-of-eratosthenes.html'),
('linear-sieve','Linear sieve','sieve','Assign each composite through its smallest prime factor exactly once.','O(n)','O(n)','The inner loop must stop at the first prime dividing the current value.','Compare smallest-prime-factor tables with Eratosthenes-based preprocessing.','algebra/prime-sieve-linear.html'),
('modular','Modular arithmetic and inverses','gcd binary-power','Normalize residues and distinguish addition, multiplication, and division via a modular inverse.','O(log m) for inverse via extended GCD','O(1)','An inverse exists only when gcd(a,m)=1; Fermat inversion requires prime modulus and nonzero residue.','Enumerate invertible residues for both prime and composite moduli.','algebra/module-inverse.html'),
('crt','Chinese remainder theorem','modular gcd','Combine congruences, checking compatibility when moduli are not coprime.','O(k log M) gcd/arithmetic steps; integer size matters','O(1) accumulation beyond inputs','Non-coprime residues must agree modulo the gcd, and the combined modulus may overflow.','Brute-force small systems, including inconsistent non-coprime cases.','algebra/chinese-remainder-theorem.html'),
('phi','Euler totient and multiplicative functions','sieve modular','Use prime factorization to count coprime residues and derive totient values.','O(sqrt n) trial factorization; O(N log log N) sieve variants','O(N) for a table','Euler’s exponent identity needs a base coprime to the modulus.','Count coprime residues directly for small n and compare.','algebra/phi-function.html'),
('primality','Miller–Rabin primality testing','binary-power modular','Test strong probable-prime witnesses using repeated squaring.','O(k log n) modular multiplications for k bases','O(1)','A fixed base set is deterministic only for its proven numeric range; modular products need safe arithmetic.','Compare against a sieve over a bounded range and include known pseudoprimes.','algebra/primality_tests.html'),
('factorization','Integer factorization and Pollard rho','primality gcd','Use randomized modular sequences and gcds to split composite factors recursively.','Randomized; no simple deterministic polynomial worst-case bound is claimed','O(log n) recursion depth in typical implementations','Handle even factors, primality checks, failed cycles, and overflow-safe modular multiplication.','Reconstruct every tested number from its prime factors.','algebra/factorization.html'),
('combinatorics','Binomial coefficients and factorial tables','modular','Choose Pascal DP or factorial/inverse-factorial methods according to n and the modulus.','O(N) table build plus O(log p) inverse; O(1) factorial-table query','O(N)','Factorial inversion under prime p fails once factorial contains p; composite moduli need different treatment.','Compare table formulas with Pascal’s triangle for small n.','combinatorics/binomial-coefficients.html'),
('inclusion-exclusion','Inclusion–exclusion','combinatorics','Correct overlapping counts by alternating over intersections of selected conditions.','O(2^k) subsets for k conditions, times intersection cost','O(k) recursion or subset state','An intersection size must count all imposed conditions together.','Count integers divisible by selected small primes and compare with a direct scan.','combinatorics/inclusion-exclusion.html'),
('matrix-power','Matrix exponentiation for recurrences','binary-power','Encode a fixed-size linear transition as matrix multiplication and exponentiate it.','O(d^3 log e) for naive d×d multiplication','O(d^2)','State order, multiplication order, and the identity matrix must match the recurrence.','Compare powered transitions against step-by-step recurrence evaluation.','algebra/binary-exp.html'),
('discrete-log','Discrete logarithms: baby-step giant-step','modular','Meet powers from two directions to solve a^x = b modulo m under stated assumptions.','O(sqrt m) expected hash operations for basic coprime variant','O(sqrt m)','The elementary variant assumes coprimality; non-coprime cases need reductions.','Compare minimal nonnegative exponents with brute force on small moduli.','algebra/discrete-log.html'),
('fft','FFT and polynomial convolution','cpp-stl-fast-io','Transform coefficients to point values, multiply pointwise, and invert the transform.','O(n log n) for padded transform length n','O(n)','Floating-point error and insufficient zero padding can corrupt integer coefficients.','Compare convolution against O(n²) multiplication on small random arrays.','algebra/fft.html'),
('ntt','Number-theoretic transforms','fft modular','Perform convolution using roots of unity in a suitable finite field.','O(n log n) for supported power-of-two length','O(n)','The modulus must support the transform length and the chosen primitive root.','Cross-check against quadratic modular convolution at every supported small length.','algebra/fft.html')]
for r in rows:advanced(a,*r)
d=module('data-structures','Data structures','cpp','Range aggregation, connectivity, persistence, and offline ordering.')
rows=[
('prefix-cpp','Prefix sums and difference arrays','cpp-stl-fast-io','Precompute cumulative aggregates or encode range additions as endpoint differences.','O(n) build; O(1) static sum query','O(n)','Inclusive and half-open endpoint conventions require different subtraction indices.','Compare range sums and reconstructed additions with a direct array model.','data_structures/fenwick.html','core'),
('fenwick','Fenwick trees','prefix-cpp','Store cumulative blocks determined by the least significant set bit.','O(log n) point update and prefix query','O(n)','One-based indices simplify lowbit loops; updating index zero never advances.','Compare random point additions and range sums against a vector.','data_structures/fenwick.html','core'),
('segment-tree','Segment trees','prefix-cpp','Represent disjoint interval aggregates using an associative merge and identity.','O(n) build; O(log n) point update and range query','O(n)','The identity must match the operation, especially for empty or negative-valued ranges.','Compare sum, minimum, and maximum queries with a direct oracle.','data_structures/segment_tree.html','core'),
('lazy-segment','Lazy propagation','segment-tree','Delay range updates using composable tags and push them before descending.','O(log n) per range update/query for compatible aggregates and tags','O(n)','Tag composition order matters; assignment and addition do not commute.','Mix range assignment, range addition, and sums against a small array.','data_structures/segment_tree.html'),
('persistent-segment','Persistent segment trees','segment-tree','Path-copy modified nodes so prior versions remain queryable.','O(log n) nodes and time per point update; O(log n) query','O(n + q log n) for q updates','Mutating a shared node corrupts older versions.','Compare every retained version with copied arrays.','data_structures/segment_tree.html'),
('dsu','Disjoint Set Union','cpp-stl-fast-io','Represent components by parent forests with union by size and path compression.','O(alpha(n)) amortized per operation','O(n)','Only representatives own valid component sizes; test for same root before merging.','Compare component equivalence with small graph traversals.','data_structures/disjoint_set_union.html','core'),
('rollback-dsu','Rollback DSU and offline dynamic connectivity','dsu segment-tree','Record reversible union changes while exploring intervals of edge activity.','O(log n) union/find without compression; offline traversal adds interval factors','O(n + recorded changes + interval storage)','Ordinary path compression creates many hidden mutations and is usually disabled for rollback.','Compare each add/remove/query timeline with rebuilding graph connectivity.','data_structures/deleting_in_log_n.html'),
('sparse-table','Sparse tables and static RMQ','cpp-stl-fast-io','Precompute aggregates for power-of-two blocks in immutable data.','O(n log n) build; O(1) idempotent RMQ query','O(n log n)','Overlapping blocks only work for idempotent operations such as min; not sum.','Compare every small interval minimum against a scan.','data_structures/sparse-table.html','core'),
('monotonic-queue','Monotonic stacks and queues','cpp-stl-fast-io','Discard elements that can never become the next useful extremum.','O(n) total push/pop work across a scan','O(n) stack or O(k) sliding window','Equal values and strict versus non-strict comparison change the meaning of nearest-greater queries.','Compare nearest greater positions and window extrema with nested loops.','data_structures/stack_queue_modification.html','core'),
('sqrt-decomposition','Square-root decomposition and Mo’s algorithm','cpp-stl-fast-io','Trade block preprocessing or query reordering for cheaper incremental changes.','Typical Mo traversal O((n+q)sqrt n) changes; each change has its own cost','O(n+q) plus maintained statistic','Mo’s algorithm requires offline queries and reversible add/remove operations.','Compare range-frequency statistics with direct counting.','data_structures/sqrt_decomposition.html'),
('treap','Treaps and implicit sequence trees','cpp-stl-fast-io','Combine ordered keys with random heap priorities; use subtree sizes for sequence positions.','Expected O(log n) split/merge/search; worst case O(n)','O(n)','Priority randomness, split boundaries, and lazy-tag push order affect correctness.','Compare random sequence insertion/deletion/reversal with a vector.','data_structures/treap.html'),
('li-chao','Li Chao trees and line envelopes','segment-tree','Keep lines that can win at selected x coordinates and recurse only where another line may improve.','O(log C) insertion/query on a bounded discrete domain C','O(C) static or O(q log C) dynamic allocation','The x domain must be explicit; evaluating m*x+b may overflow.','Compare minimum line values against checking every inserted line.','geometry/convex_hull_trick.html')]
for r in rows:advanced(d,*r)
p=module('dynamic-programming','Dynamic programming','cpp','States, recurrences, dependency order, and proof-driven optimizations.')
rows=[
('dp-foundations','DP state design and memoization','cpp-stl-fast-io','Define an exact state, base cases, transition, and dependency order to reuse overlapping subproblems.','Number of states × work per transition','Number of retained states','An uncomputed state must not be confused with a valid zero answer.','Compare a tiny exhaustive search with a tabulated recurrence.','dynamic_programming/intro-to-dp.html','core'),
('knapsack','0/1, unbounded, and bounded knapsack','dp-foundations','Track the best value or reachability at each capacity while respecting each item’s multiplicity.','O(nW) for 0/1 and unbounded variants','O(W) with correct compressed update order','Descending capacity prevents reusing a 0/1 item; ascending capacity permits unbounded reuse.','Enumerate item subsets for small 0/1 instances and compare.','dynamic_programming/knapsack.html','core'),
('lis','Longest increasing subsequence','dp-foundations','Maintain either predecessor DP or the smallest attainable tail for each subsequence length.','O(n log n) tails method','O(n) with reconstruction','Strict versus nondecreasing sequences select lower_bound versus upper_bound.','Compare lengths with O(n²) DP and validate reconstructed subsequences.','sequences/longest_increasing_subsequence.html','core'),
('interval-dp','Interval DP','dp-foundations','Build answers for subintervals in increasing length by choosing a split or endpoint action.','Often O(n³) for all interval splits','O(n²)','Every dependency must refer to a smaller, already computed interval.','Compare matrix-chain or merging costs with exhaustive split trees.','dynamic_programming/intro-to-dp.html'),
('tree-dp','Tree DP and subtree states','dp-foundations graph-dfs','Root a tree and merge children’s states after their subtrees are solved.','O(n) for constant-size states; larger merges can cost more','O(n)','Do not count the parent as a child, and separate states with different boundary conditions.','Compare maximum independent-set size with subset enumeration on tiny trees.','dynamic_programming/intro-to-dp.html'),
('rerooting','Rerooting DP','tree-dp','Propagate outside-subtree information so every vertex can be evaluated as a root.','O(n) for constant-time associative child merges','O(n)','Compute a child’s outside contribution without including that child twice.','Compare all-root distance sums against BFS from each vertex.','graph/tree_painting.html'),
('bitmask-dp','Bitmask DP over subsets','dp-foundations','Encode a small chosen set in bits and add a position or last element to the state.','O(n² 2^n) for subset TSP; problem-specific','O(n 2^n) for last-vertex state','Shift widths, masks outside the universe, and double-counted orders can break the state.','Compare small assignment or traveling-salesperson instances with permutations.','algebra/all-submasks.html'),
('sos-dp','Sum-over-subsets DP','bitmask-dp','Propagate aggregates across individual bits to combine contributions of all submasks.','O(n 2^n) for n bits','O(2^n)','The update direction distinguishes submask from supermask aggregation.','Compare every mask against explicit submask enumeration.','algebra/all-submasks.html'),
('digit-dp','Digit DP','dp-foundations','Process a number’s digits with a tight flag and property-specific state.','Digits × states × digit choices','States per layer or full memo table','Leading zeros and whether zero itself is counted must be specified.','Count a digit property over small intervals by enumeration.','dynamic_programming/intro-to-dp.html'),
('profile-dp','Broken-profile DP','bitmask-dp','Move a frontier through a narrow grid while recording its occupied boundary cells.','Exponential in frontier width; polynomial in grid length','Typically O(2^width) state storage','The mask describes a specific boundary, not an arbitrary subset of cells.','Compare domino tilings of tiny rectangles with backtracking.','dynamic_programming/profile-dynamics.html'),
('divide-conquer-dp','Divide-and-conquer DP optimization','interval-dp','Use monotonic optimal split positions to reduce transition searches.','Often O(k n log n) for k layers','O(n) per pair of layers','Monotone optima must be proved for the cost function, not guessed from examples.','Compare optimized layers with quadratic transition enumeration.','dynamic_programming/divide-and-conquer-dp.html'),
('knuth-dp','Knuth optimization','interval-dp','Restrict interval split searches using neighboring optimal split bounds.','O(n²) when the required cost conditions hold','O(n²)','The quadrangle/monotonicity conditions are not universal; a wrong cost invalidates the bound.','Cross-check every small interval against cubic DP.','dynamic_programming/knuth-optimization.html')]
for r in rows:advanced(p,*r)
s=module('strings','String processing','cpp','Borders, pattern matching, tries, hashing, and suffix structures.')
rows=[
('prefix-function','Prefix function and KMP','cpp-stl-fast-io','Track the longest border of each prefix and fall back through previously computed borders.','O(n+m) matching text length n and pattern length m','O(m) pattern table','After a mismatch, reuse border information; overlapping matches must remain possible.','Compare all match positions with naive substring checking.','string/prefix-function.html','core'),
('z-function','Z-function','cpp-stl-fast-io','Reuse a known prefix-matching interval to compute matches starting at each position.','O(n)','O(n)','Choose an inclusive or half-open Z-box convention and keep updates consistent.','Compare each Z value with direct character matching.','string/z-function.html','core'),
('trie','Tries and prefix dictionaries','cpp-stl-fast-io','Represent shared string prefixes as paths whose terminal markers record complete words.','O(total input characters) build; O(word length) search','O(total characters × alphabet storage choice)','A path’s existence does not imply that a complete word ends there.','Compare exact and prefix queries with a set of strings.','string/aho_corasick.html','core'),
('string-hash','Polynomial rolling hashes','modular prefix-cpp','Map substrings to comparable polynomial residues with consistent normalization.','O(n) preprocessing; O(1) fixed-substring hash query','O(n)','Collisions are possible; hash equality alone is not a deterministic proof of string equality.','Compare hash-based decisions with direct comparisons on small random inputs.','string/string-hashing.html'),
('aho-corasick','Aho–Corasick multiple-pattern matching','trie prefix-function','Add failure links to a trie so text can be scanned while following suffix-compatible states.','O(total pattern length × alphabet handling + text length + reported matches)','O(total pattern length × alphabet handling)','Terminal outputs from failure-linked states must be propagated or followed correctly.','Compare all pattern match positions with naive independent searches.','string/aho_corasick.html'),
('suffix-array','Suffix arrays and LCP','cpp-stl-fast-io','Order suffixes lexicographically, then compute shared-prefix lengths between neighbors.','O(n log n) doubling with counting sort; O(n) LCP','O(n)','Sentinel choice and rank boundaries must respect the alphabet and string end.','Compare with explicitly sorted suffix strings on tiny inputs.','string/suffix-array.html'),
('suffix-automaton','Suffix automata','trie','Represent end-position equivalence classes of substrings using states and suffix links.','O(n) for fixed-alphabet transitions; map transitions add factors','O(n) states and transitions for fixed alphabet bounds','Clone states inherit transitions but have carefully adjusted lengths and occurrence treatment.','Compare the number of distinct substrings with a set of all small substrings.','string/suffix-automaton.html'),
('manacher','Manacher’s palindrome algorithm','z-function','Reuse mirrored palindrome radii while extending the rightmost known palindrome.','O(n)','O(n)','Odd and even palindromes use different centers and boundary formulas.','Compare every palindrome radius against direct expansion.','string/manacher.html'),
('lyndon','Lyndon factorization and minimal rotation','cpp-stl-fast-io','Decompose a string into ordered Lyndon words using linear comparisons.','O(n)','O(1) auxiliary state, excluding factor output','Index advancement must skip entire established blocks to retain linear time.','Compare minimum rotations with enumerating all rotations.','string/lyndon_factorization.html')]
for r in rows:advanced(s,*r)
g=module('graphs','Graph algorithms','cpp','Traversals, shortest paths, spanning structure, flow, and matching.')
rows=[
('graph-model','Graph representations and invariants','cpp-stl-fast-io','Translate vertices and edges into adjacency lists, matrices, or edge lists according to the operations needed.','O(V+E) adjacency-list construction','O(V+E)','Undirected edges need both directions; self-loops and parallel edges may require distinct edge IDs.','Build a graph and compare degree sums with the input edge count.','graph/breadth-first-search.html','core'),
('graph-bfs','BFS and unweighted shortest paths','graph-model','Use a first-in-first-out queue to visit vertices in nondecreasing edge distance.','O(V+E)','O(V)','Mark on enqueue; shortest-path guarantees require equal edge weights.','Compare distances with all-pairs shortest paths on tiny unweighted graphs.','graph/breadth-first-search.html','core'),
('graph-dfs','DFS and connected components','graph-model','Follow a path deeply using recursion or an explicit stack and retain a visited invariant.','O(V+E)','O(V)','Recursion can overflow on long paths; traverse from every unvisited vertex for all components.','Compare component assignments with DSU on small undirected graphs.','graph/depth-first-search.html','core'),
('topological','Topological sorting and DAG DP','graph-dfs dp-foundations','Order dependencies in an acyclic directed graph and evaluate states in that order.','O(V+E)','O(V)','A directed cycle means no topological order exists; detect incomplete processing or back edges.','Check every edge goes forward in the returned order.','graph/topological-sort.html','core'),
('dijkstra','Dijkstra’s shortest paths','graph-model cpp-stl-fast-io','Repeatedly settle the smallest tentative distance using nonnegative edge weights.','O((V+E) log V) with a binary heap','O(V+E)','Negative edges invalidate the greedy argument; discard stale heap entries and guard addition overflow.','Compare with Bellman–Ford on small nonnegative graphs.','graph/dijkstra_sparse.html','core'),
('zero-one-bfs','0–1 BFS','graph-bfs','Use a deque to prioritize distance-preserving edges before unit-cost edges.','O(V+E)','O(V+E)','Weights must be exactly zero or one; larger weights break the deque ordering argument.','Cross-check with Dijkstra on random zero/one graphs.','graph/01_bfs.html'),
('bellman-ford','Bellman–Ford and negative cycles','graph-model','Relax all edges repeatedly and use an extra pass to detect reachable improvements.','O(VE)','O(V)','Unreachable infinity values must not participate in arithmetic; cycle relevance depends on reachability.','Compare finite distances with exhaustive bounded walks on tiny graphs.','graph/bellman_ford.html'),
('floyd-warshall','Floyd–Warshall','graph-model dp-foundations','Allow intermediate vertices one at a time in an all-pairs shortest-path DP.','O(V³)','O(V²)','The intermediate vertex is the outer loop; skip infinity additions and interpret negative cycles.','Compare with running Bellman–Ford from each vertex.','graph/all-pair-shortest-path-floyd-warshall.html'),
('mst-kruskal','Minimum spanning trees: Kruskal','dsu graph-model','Process edges by weight and add an edge only if it joins distinct components.','O(E log E)','O(V+E)','A disconnected graph yields a spanning forest, not a spanning tree.','Enumerate spanning trees on tiny graphs and compare total weights.','graph/mst_kruskal_with_dsu.html','core'),
('mst-prim','Minimum spanning trees: Prim','graph-model cpp-stl-fast-io','Grow a connected set by repeatedly choosing its lightest outgoing connection.','O(E log V) heap variant; O(V²) dense variant','O(V+E) heap representation','Do not confuse edge connection cost with the accumulated path distance from Dijkstra.','Compare total weight with Kruskal, including duplicate and negative weights.','graph/mst_prim.html'),
('scc','Strongly connected components','graph-dfs','Partition a directed graph by mutual reachability and form its acyclic condensation graph.','O(V+E)','O(V+E)','Finishing order and reversed edges serve specific roles; reversing only one part breaks Kosaraju.','Compare component equivalence with pairwise reachability.','graph/strongly-connected-components.html'),
('bridges','Bridges and articulation points','graph-dfs','Track discovery times and low-link reachability through DFS tree edges and back edges.','O(V+E)','O(V+E)','Parallel edges require edge IDs; skipping every edge to the parent can invent bridges.','Remove each edge or vertex in a tiny graph and recount components.','graph/bridge-searching.html'),
('lca','Lowest common ancestor and binary lifting','graph-dfs','Precompute power-of-two ancestors and lift vertices to a common depth and ancestor.','O(V log V) preprocessing; O(log V) query','O(V log V)','Root handling and ancestor sentinels must avoid invalid indices.','Compare with a parent-by-parent climb on random small trees.','graph/lca_binary_lifting.html'),
('hld','Heavy-light decomposition','lca segment-tree','Split tree paths into logarithmically many heavy-chain intervals for range structures.','O(log² V) path queries with a segment tree','O(V)','Vertex-weight and edge-weight paths have different endpoint inclusion rules.','Compare random path aggregates with explicit path reconstruction.','graph/hld.html'),
('euler','Euler trails and Hierholzer’s algorithm','graph-model','Consume each edge exactly once while splicing cycles or using an explicit path stack.','O(V+E)','O(V+E)','Degree conditions alone are insufficient without the relevant connectivity condition.','Check that every input edge ID appears exactly once in a returned trail.','graph/euler_path.html'),
('max-flow','Residual networks and augmenting paths','graph-bfs','Represent remaining capacity and reverse cancellation edges while augmenting source-to-sink flow.','O(VE²) for Edmonds–Karp','O(V+E)','Every forward edge needs a paired reverse edge, including correct indexing for parallel edges.','Compare maximum flow with all source-side cuts on tiny graphs.','graph/edmonds_karp.html'),
('dinic','Dinic’s maximum flow','max-flow','Build a level graph and send a blocking flow using current-edge pointers.','O(V²E) general bound; better bounds require special graph structure','O(V+E)','Reset pointers per level graph and retain reverse-edge capacity updates.','Cross-check against Edmonds–Karp and enumerate minimum cuts.','graph/dinic.html'),
('matching','Bipartite matching','graph-dfs max-flow','Increase matching size along alternating augmenting paths in a bipartite graph.','O(VE) for a simple augmenting-path implementation','O(V+E)','The graph must be bipartite and matched endpoints must remain unique.','Compare with subset enumeration for tiny bipartite graphs.','graph/kuhn_maximum_bipartite_matching.html'),
('min-cost-flow','Minimum-cost flow and potentials','max-flow dijkstra bellman-ford','Augment flow while minimizing cost using residual reverse costs and shortest paths.','For successive unit augmentations, O(F E log V) plus potential initialization under applicable assumptions','O(V+E)','Negative reverse costs require valid potentials or a suitable shortest-path method; watch total cost overflow.','Compare with enumerated feasible flows on tiny networks.','graph/min_cost_flow.html'),
('two-sat','2-SAT and implication graphs','scc','Encode each binary clause as implications and detect contradictory literal components.','O(V+E) in the implication graph','O(V+E)','Negating a literal must map to its paired node; assignment depends on the SCC ordering convention.','Compare satisfiability and assignments with exhaustive Boolean assignments.','graph/2SAT.html')]
for r in rows:advanced(g,*r)
h=module('geometry','Computational geometry','cpp','Orientation, intersections, polygons, hulls, and robust numeric decisions.')
rows=[
('geometry-vectors','Points, vectors, dot and cross products','cpp-stl-fast-io','Represent geometric relations with coordinate differences, dot products, and signed area.','O(1) per primitive','O(1)','Coordinate products and differences may overflow; choose bounds and wider arithmetic before multiplying.','Check orientation identities on collinear and axis-aligned triples.','geometry/basic-geometry.html','core'),
('segment-intersection','Segment intersection','geometry-vectors','Combine orientation signs with bounding checks to handle crossing and collinear overlap.','O(1) per pair','O(1)','Endpoints, zero-length segments, and collinear overlap need explicit treatment.','Enumerate small integer-coordinate segments and compare with a rational reference.','geometry/check-segments-intersection.html'),
('polygon-area','Polygon area and orientation','geometry-vectors','Sum directed edge cross products to compute twice the signed polygon area.','O(n)','O(1) beyond vertex input','Close the polygon edge cycle and distinguish signed from absolute area.','Compare rectangles and triangulated small polygons with known areas.','geometry/area-of-simple-polygon.html','core'),
('point-in-polygon','Point-in-polygon queries','segment-intersection','Count ray crossings or use winding information while handling boundary points separately.','O(n) for a general n-vertex polygon','O(1)','A ray through a vertex can be counted twice without a consistent half-open crossing rule.','Test interior, exterior, vertices, and points on horizontal edges.','geometry/point-in-convex-polygon.html'),
('convex-hull','Convex hull by monotone chain','geometry-vectors sorting-placeholder','Sort points and maintain lower/upper chains by removing turns that violate convexity.','O(n log n)','O(n)','Choose whether boundary-collinear points remain, and remove duplicate input points deliberately.','Check all input points lie on or inside the hull and compare small exhaustive candidates.','geometry/convex-hull.html'),
('convex-queries','Point in a convex polygon','convex-hull','Use orientation against a fixed anchor to binary-search the containing angular wedge.','O(log n) per query after ordered preprocessing','O(n) stored polygon','The polygon must be convex with consistent order and boundary conventions.','Compare with a general point-in-polygon implementation.','geometry/point-in-convex-polygon.html'),
('rotating-calipers','Rotating calipers','convex-hull','Advance supporting contacts monotonically around a convex polygon to inspect extremal pairs.','O(n) after the hull for standard diameter traversal','O(1) additional state','Ties and collinear hull edges can require checking more than one antipodal candidate.','Compare diameter with checking every pair of hull vertices.','geometry/convex-hull.html'),
('closest-pair','Closest pair of points','geometry-vectors','Divide by one coordinate and bound candidate comparisons in a narrow sorted strip.','O(n log n)','O(n)','Repeated sorting in every recursive merge can add an extra logarithmic factor.','Compare squared distances with every pair on small random point sets.','geometry/nearest_points.html'),
('line-circle','Line, circle, and circle-circle intersection','geometry-vectors','Reduce intersections to algebraic distance and projection calculations with explicit degeneracies.','O(1) per pair of primitives','O(1)','Tangency, coincident circles, and near-zero discriminants need a declared numeric policy.','Check constructed intersections satisfy both original equations within the chosen tolerance.','geometry/circle-circle-intersection.html'),
('half-plane','Half-plane intersection','segment-intersection convex-hull','Order directed half-planes and maintain an intersection deque after removing invalid boundaries.','O(n log n)','O(n)','Parallel boundaries, empty intersections, and unbounded regions require explicit handling.','Compare small bounded instances with polygon clipping.','geometry/halfplane-intersection.html')]
for r in rows:
 r=list(r);r[2]=r[2].replace(' sorting-placeholder','');advanced(h,*r)
curriculum=dict(schema_version='2.0.0',title='Forge · C, C++ and the Algorithm Atlas',primary_standards={'c':'C17','cpp':'C++17'},authorship='Original explanations, study plans, exercises, and templates; topic coverage inspired by cp-algorithms.com. External articles retain their own licenses.',scope_note='This is a long-term map, not a claim that all advanced topics fit into 20 or 40 days. Complete lessons and blueprints are explicitly distinguished.',recommended_path=['cpp-foundations','cpp-stl','algebra','data-structures','dynamic-programming','graphs','strings','geometry'],optional_path=['c-foundations'],learning_policy={'prerequisite_gate':'Complete prerequisite lessons before recording completion. Blueprints are study plans and cannot be marked completed in the site.','review':'Add cards after a completed lesson; retrieve before reveal; rate honestly.','transfer':'Reconstruct code from memory, then solve an unseen variation.','deadline':'Prefer foundations and event-relevant patterns before advanced breadth.'},modules=modules)
ids={l['id'] for m in modules for l in m['lessons']}
assert len(ids)==sum(len(m['lessons']) for m in modules)
for m in modules:
 for l in m['lessons']:
  assert set(l['prerequisites'])<=ids,(l['id'],l['prerequisites'])
(ROOT/'content/curriculum.json').write_text(json.dumps(curriculum,ensure_ascii=False,indent=2)+'\n')
print(len(modules),'modules;',len(ids),'topics;',sum(l['content_status']=='complete' for m in modules for l in m['lessons']),'complete lessons')
